### ISSUE TITLE
RMSD progressmeter string isn't formated correctly

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1084]
### Expected behaviour

The following message should be the verbose output of an RMSD calculation

```
RMSD 5.2 A at frame 10/100  [1.0 %]
```
### Actual behaviour

```
RMSD %(rmsd)5.2f A at frame %(step)5d/%(numsteps)d  [%(percentage)5.1f%%]
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
from MDAnalysis.analysis import rms

u = mda.Universe(top, trj)
rms.RMSD(u, quiet=False)
....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.16.0dev

**Comment by tylerjereddy** [comment]
Running `nosetests test_rms.py` produces a traceback related to the new `mmtf` stuff:
```
======================================================================
ERROR: Failure: ImportError (No module named mmtf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/treddy/anaconda/envs/scipy_dev/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/treddy/anaconda/envs/scipy_dev/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/treddy/anaconda/envs/scipy_dev/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/treddy/python_modules/MDAnalysis/MDA_dev/mdanalysis/testsuite/MDAnalysisTests/analysis/test_rms.py", line 20, in <module>
    import MDAnalysis
  File "/Users/treddy/python_modules/MDAnalysis/MDA_dev/mdanalysis/package/MDAnalysis/__init__.py", line 174, in <module>
    from .coordinates.core import writer as Writer
  File "/Users/treddy/python_modules/MDAnalysis/MDA_dev/mdanalysis/package/MDAnalysis/coordinates/__init__.py", line 712, in <module>
    from . import PDB
  File "/Users/treddy/python_modules/MDAnalysis/MDA_dev/mdanalysis/package/MDAnalysis/coordinates/PDB.py", line 152, in <module>
    from ..topology.core import guess_atom_element
  File "/Users/treddy/python_modules/MDAnalysis/MDA_dev/mdanalysis/package/MDAnalysis/topology/__init__.py", line 277, in <module>
    from . import MMTFParser
  File "/Users/treddy/python_modules/MDAnalysis/MDA_dev/mdanalysis/package/MDAnalysis/topology/MMTFParser.py", line 62, in <module>
    import mmtf
ImportError: No module named mmtf
```

Probably best if this is resolved before I add another test in there.

**Comment by kain88-de** [comment]
Does this happen on Travis?  Did you install mmtf locally.

**Comment by tylerjereddy** [comment]
So there's a new dependency that's not being handled by the setup / build procedure?

**Comment by richardjgowers** [comment]
https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.py#L487

I put it here under `requires` but it seems that does nothing on install, and instead we're meant to use `install_requires`.  I think `requires` ends up on the PyPI page metadata for the package, rather than be useful during install time.  Should probably combine these two to keep things DRY?
