### ISSUE TITLE
IOError in MDAnalysis/coordinates/TRZ.py", line 242, in _read_trz_header on big-endian arches

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/mdanalysis#1424]
### Expected behaviour
Testsuite passes.

### Actual behaviour
67 tests fail with:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 381, in setUp
    try_run(self.inst, ('setup', 'setUp'))
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/builddir/build/BUILD/MDAnalysis-0.16.1/MDAnalysisTests-0.16.1/MDAnalysisTests/analysis/test_hydrogenbondautocorrel.py", line 37, in setUp
    u = self.u = mda.Universe(TRZ_psf, TRZ)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/core/universe.py", line 278, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/core/universe.py", line 426, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/coordinates/TRZ.py", line 175, in __init__
    self._read_trz_header()
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.16.1-2.fc27.ppc64/usr/lib64/python2.7/site-packages/MDAnalysis/coordinates/TRZ.py", line 242, in _read_trz_header
    raise IOError
IOError: 
```

### Code to reproduce the behaviour

Run the testsuite on a big-endian arch like ppc64 or s390x. Example failure on ppc64: https://koji.fedoraproject.org/koji/taskinfo?taskID=20061305 (see build.log).

### Current version of MDAnalysis:
0.16.1

**Comment by rathann** [comment]
Apparently, the TRZ file format is little-endian. Patch incoming.

**Comment by kain88-de** [comment]
you mean the files we have are all little-endian? Or did you find some actual reference or standard description of the format online?

**Comment by richardjgowers** [comment]
the files don't exactly have a standard, they're just written by a Fortran `write(*,*)` , which iirc follows the endianness of whatever is writing it.
