### ISSUE TITLE
Python 3 I/O operation issue

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#1506]
Travis is reporting some errors of this nature with Python 3:

```
Exception ignored in: <bound method NamedStream.__del__ of <NamedStream(/home/travis/miniconda/envs/test/lib/python3.6/site-packages/MDAnalysisTests/data/adk_open.pdb, /home/travis/miniconda/envs/test/lib/python3.6/site-packages/MDAnalysisTests/data/adk_open.pdb)>>

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/MDAnalysis/lib/util.py", line 690, in __del__

    self.close(force=True)

  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/MDAnalysis/lib/util.py", line 681, in close

    return self.stream.close()

  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/MDAnalysis/lib/util.py", line 686, in close

    self.reset()

  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/MDAnalysis/lib/util.py", line 631, in reset

    self.stream.seek(0)  # typical file objects

ValueError: I/O operation on closed file
```

**Comment by kain88-de** [comment]
Does this still occur in the latest master? I haven't seen that on travis today.

**Comment by tylerjereddy** [comment]
Occurs on develop: https://travis-ci.org/MDAnalysis/mdanalysis/jobs/254704373

**Comment by tylerjereddy** [comment]
This appears to have disappeared so I'm closing it, but it is good to have a record of it because I'm not exactly sure which fix 'accidentally' repaired this.
