### ISSUE TITLE
Python 3.4/3.5 I/O in tests

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#1530]
The full Python 3 Travis CI build matrix passes, but there is an ignored exception:

```
Exception ignored in: <bound method ReaderBase.__del__ of <PDBReader None with 1 frames of 2 atoms>>

Traceback (most recent call last):

  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/MDAnalysis/coordinates/base.py", line 1780, in __del__

    self.close()

  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/MDAnalysis/coordinates/PDB.py", line 404, in close

    self._pdbfile.close()

  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/MDAnalysis/lib/util.py", line 696, in close

    self.reset()

  File "/home/travis/miniconda/envs/test/lib/python3.5/site-packages/MDAnalysis/lib/util.py", line 638, in reset

    self.stream.seek(0)  # typical file objects

ValueError: I/O operation on closed file
```

@richardjgowers and I speculate that the file stream handling change in Python 3.6 may explain why there's no ignored exception in the latter.

**Comment by tylerjereddy** [comment]
This may be during the 'teardown' of a test, so not so critical.

**Comment by kain88-de** [comment]
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/255799078

happens again often in #1517

**Comment by kain88-de** [comment]
btw the exceptions are ignored because they occur in a `__del__` method.
