### ISSUE TITLE
Can't run benchmarks with asv

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1577]
### Expected behaviour

`asv run -e -s 20 ddb57592..e0bc3034` runs all benchmarks that we have

### Actual behaviour

Doesn't install `MDAnalysisTests`. The MDAnalysis package is installed though.

```
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py2.7-Cython-mock-nose-numpy-psutil-pytest-scipy-six
·· Installing into conda-py2.7-Cython-mock-nose-numpy-psutil-pytest-scipy-six.
·· Error running /home/max/foss/molecular-dynamics/mdanalysis/mdanalysis/benchmarks/env/17f51c85156bb4ac31b052ed216e9d94/bin/python /home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py discover /home/max/foss/molecular-dynamics/mdanalysis/mdanalysis/benchmarks/benchmarks /tmp/tmpaxl8kkin
             STDOUT -------->
             
             STDERR -------->
             Traceback (most recent call last):
               File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py", line 867, in <module>
                 commands[mode](args)
               File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py", line 812, in main_discover
                 list_benchmarks(benchmark_dir, fp)
               File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py", line 797, in list_benchmarks
                 for benchmark in disc_benchmarks(root):
               File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py", line 696, in disc_benchmarks
                 for module in disc_files(root, os.path.basename(root) + '.'):
               File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py", line 648, in disc_files
                 module = import_module(package + filename)
               File "/home/max/foss/molecular-dynamics/mdanalysis/mdanalysis/benchmarks/env/17f51c85156bb4ac31b052ed216e9d94/lib/python2.7/importlib/__init__.py", line 37, in import_module
                 __import__(name)
               File "/home/max/foss/molecular-dynamics/mdanalysis/mdanalysis/benchmarks/benchmarks/GRO.py", line 5, in <module>
                 from MDAnalysisTests.datafiles import GRO
             ImportError: No module named MDAnalysisTests.datafiles
Traceback (most recent call last):
  File "/home/max/anaconda3/bin/asv", line 11, in <module>
    load_entry_point('asv==0.3.dev1124+79c25765', 'console_scripts', 'asv')()
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/main.py", line 38, in main
    result = args.func(args)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/commands/__init__.py", line 48, in run_from_args
    return cls.run_from_conf_args(conf, args)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/commands/run.py", line 127, in run_from_conf_args
    **kwargs
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/commands/run.py", line 185, in run
    benchmarks = Benchmarks(conf, repo, environments, regex=bench)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmarks.py", line 336, in __init__
    benchmarks = self.disc_benchmarks(conf, repo, environments)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmarks.py", line 385, in disc_benchmarks
    dots=False)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/plugins/conda.py", line 150, in run
    return self.run_executable('python', args, **kwargs)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/environment.py", line 561, in run_executable
    return util.check_output([exe] + args, **kwargs)
  File "/home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/util.py", line 571, in check_output
    raise ProcessError(args, retcode, stdout, stderr)
asv.util.ProcessError: Command '/home/max/foss/molecular-dynamics/mdanalysis/mdanalysis/benchmarks/env/17f51c85156bb4ac31b052ed216e9d94/bin/python /home/max/anaconda3/lib/python3.6/site-packages/asv-0.3.dev1124+79c25765-py3.6-linux-x86_64.egg/asv/benchmark.py discover /home/max/foss/molecular-dynamics/mdanalysis/mdanalysis/benchmarks/benchmarks /tmp/tmpaxl8kkin' returned non-zero exit status 1
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

**Comment by tylerjereddy** [comment]
- unless we can get `MDAnalysisTests` into the default conda channel, I'll have to further hack our fork / branch of asv until the pertinent functionality to specify custom conda channels for the JSON dependency matrix actually makes it into the asv package itself--see the request (from another dev / library user) [here](https://github.com/spacetelescope/asv/issues/405)
- either that or we switch to virtualenv / pip for the asv builds (but I'd rather not switch it all over just because of this, and I think the virtual env installs were pretty slow when I tried them in the past)
- the benchmarks should also work if you have either Python 2 or 3 local installs of MDAnalysisTests, but I would agree we should not have to depend on the local install state of the test suite

**Comment by kain88-de** [comment]
I do have local installs in my conda installation didn't help. Pip builds might be quick now for versions that have prebuilt wheels.
