### ISSUE TITLE
DCD not loaded in python 3.5 installation of MDAnalysis 0.16.2 

### ISSUE THREAD

**Issue by jmborr** [MDAnalysis/mdanalysis#1749]
Ubuntu 16.04
No troubles with python 2.7, but with python 3.5 I get this error:
```
leioa:~> python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
>>> import MDAnalysis as mda
(warning message omitted)
>>> mda.__version__
'0.16.2'
>>> u = mda.Universe('./hiAPP.pdb', './hiAPP.dcd')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/MDAnalysis/core/_get_readers.py", line 98, in get_reader_for
    return _READERS[format]
KeyError: 'DCD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/MDAnalysis/core/universe.py", line 426, in load_new
    reader = get_reader_for(filename, format=format)
  File "/usr/local/lib/python3.5/dist-packages/MDAnalysis/core/_get_readers.py", line 108, in get_reader_for
    format, filename, _READERS.keys()))
ValueError: Unknown coordinate trajectory format 'DCD' for './hiAPP.dcd'. The FORMATs 
           dict_keys(['MEMORY', 'DMS', 'RESTRT', 'MMTF', 'ENT', 'INPCRD', 'TRJ', 'MOL2', 'PDB', 'PQR', 'NC', 'HISTORY', 'CRDBOX', 'GRO', 'CONFIG', 'TRZ', 'TRR', 'CRD', 'NCDF', 'XPDB', 'MDCRD', 'XTC', 'PDBQT', 'GMS', 'XYZ', 'CHAIN'])
           are implemented in MDAnalysis.
           See http://docs.mdanalysis.org/documentation_pages/coordinates/init.html#id1
           Use the format keyword to explicitly set the format: 'Universe(...,format=FORMAT)'
           For missing formats, raise an issue at http://issues.mdanalysis.org

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/MDAnalysis/core/universe.py", line 283, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/MDAnalysis/core/universe.py", line 430, in load_new
    "           {1}".format(filename, err))
TypeError: Cannot find an appropriate coordinate reader for file './hiAPP.dcd'.
           Unknown coordinate trajectory format 'DCD' for './hiAPP.dcd'. The FORMATs 
           dict_keys(['MEMORY', 'DMS', 'RESTRT', 'MMTF', 'ENT', 'INPCRD', 'TRJ', 'MOL2', 'PDB', 'PQR', 'NC', 'HISTORY', 'CRDBOX', 'GRO', 'CONFIG', 'TRZ', 'TRR', 'CRD', 'NCDF', 'XPDB', 'MDCRD', 'XTC', 'PDBQT', 'GMS', 'XYZ', 'CHAIN'])
           are implemented in MDAnalysis.
           See http://docs.mdanalysis.org/documentation_pages/coordinates/init.html#id1
           Use the format keyword to explicitly set the format: 'Universe(...,format=FORMAT)'
           For missing formats, raise an issue at http://issues.mdanalysis.org
```

**Comment by kain88-de** [comment]
Only the dev version supports python 3. We aim for a release around new year.

**Comment by jmborr** [comment]
nice! :smile:
