### ISSUE TITLE
Adding velocity to an atomgroup

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1754]
I'm trying to add velocity to a Universe. I have tried to add them according to the new topology system but it seems that the velocity is not in the `MDAnalysis.core.topologyattrs`.

### Expected behaviour
Velocity being added to the Universe and saved as gro file

### Actual behaviour
```python
Traceback (most recent call last):
  File "~/software/mdanalysis/package/MDAnalysis/core/universe.py", line 706, in add_TopologyAttr
    tcls = _TOPOLOGY_ATTRS[topologyattr]
KeyError: 'velocities'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "~/software/pycharm-2017.3.2/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "~/software/pycharm-2017.3.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "setup.py", line 22, in <module>
    em.add_TopologyAttr('velocities')
  File "~/software/mdanalysis/package/MDAnalysis/core/universe.py", line 713, in add_TopologyAttr
    topologyattr, ', '.join(sorted(_TOPOLOGY_ATTRS.keys())))
ValueError: Unrecognised topology attribute name: 'velocities'.  Possible values: 'altLoc, altLocs, angles, atomattr, atomattrs, atomiccharge, atomiccharges, atomnum, atomnums, bfactor, bfactors, bonds, chainID, chainIDs, charge, charges, dihedrals, element, elements, icode, icodes, id, ids, impropers, index, indices, mass, masses, model, models, moltype, moltypes, name, names, occupancies, occupancy, radii, radius, resid, resids, residueattr, residueattrs, resindex, resindices, resname, resnames, resnum, resnums, segid, segids, segindex, segindices, segmentattr, segmentattrs, tempfactor, tempfactors, topologyattr, topologyattrs, type, type_index, type_indices, types'
To raise an issue go to: http://issues.mdanalysis.org
```

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('md.gro')
# u has velocity
em = mda.Universe('em.gro')
# em didn't have velocity
em.add_TopologyAttr('velocities')
em.atoms.velocities = u.atoms.velocities
# Both em and u has the same number of atoms
em.atoms.write('npt.gro')
```

### Currently version of MDAnalysis:
py36/mda 0.17.0

**Comment by richardjgowers** [comment]
Hi @xiki-tempula 

This admittedly isn't very clear but velocities aren't part of the Topology, they're a trajectory thing.  

The following should work:
```python
u = mda.Universe()
# set the has_velocities flag on the Timestep
u.trajectory.ts.has_velocities = True

# u.atoms.velocities now works
u.atoms.velocities = md.atoms.velocities

```

Let me know if that works for you

It's a little ugly to have to set the flag on the Timestep, maybe it should be possible from the AtomGroup

**Comment by xiki-tempula** [comment]
@richardjgowers Thank you very much for the help. This works.

**Comment by jht0664** [comment]
@richardjgowers 
I applied this to put velocities on **trajectory**, but it does not work.
Although I assigned all velocities at the different time step, only velocities in the last frame were assigned into all time frames. 

```
u = mda.Universe('init.pdb','md_nvt_pos.dcd')
uv = mda.Universe('init.pdb','md_nvt_vel.dcd')

# set the has_velocities flag on the Timestep
u.trajectory.ts.has_velocities = True

# assign velocities to u
for iframe in range(len(u.trajectory)):
	ts=u.trajectory[iframe]
	tsv=uv.trajectory[iframe]
	u.atoms.velocities = copy.copy(uv.atoms.positions)
	print(u.atoms.velocities[0])

# check result
for iframe in range(len(u.trajectory)):
	ts=u.trajectory[iframe]
	print(u.atoms.velocities[0])
```

the first for loop shows:
```
[0 0 0]
[ 3.8088248 -2.0670774 -4.183966 ]
[-1.0640373  -1.3062657   0.35862523]

```

But the second for loop for result shows:
```
[-1.0640373  -1.3062657   0.35862523]
[-1.0640373  -1.3062657   0.35862523]
[-1.0640373  -1.3062657   0.35862523]

```
