### ISSUE TITLE
TPRParser does not support TPX version 112 from Gromacs 2018

### ISSUE THREAD

**Issue by erlendurj** [MDAnalysis/mdanalysis#1796]
MDAnalysis 0.17.0 fails to open .tpr files of Gromacs 2018. The minimal example I can think as an example results in the following error:
>>> import MDAnalysis as MDA
>>> u = MDA.Universe('ef0_nemd_base0028.tpr','ef0_nemd_base0028.trr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/MDAnalysis/core/universe.py", line 280, in __init__
    "Error: {2}".format(self.filename, parser, err))
ValueError: Failed to construct topology from file ef0_nemd_base0028.tpr with parser <class 'MDAnalysis.topology.TPRParser.TPRParser'>.
Error: Your tpx version is 112, which this parser does not support, yet

**Comment by orbeckst** [comment]
TODO
- [ ] build Gromacs 2018 TPR (same system as the other TPRs)
- [ ] hack TPR parser
- [ ] write test

**Comment by jbarnoud** [comment]
I updated the tests, I'll fix the parser itself latter this week.

**Comment by jbarnoud** [comment]
Having the TPR parser pass the tests was surprisingly easy. Yet, the tests are based on older file that get converted. Would somebody have a TPR that use the latest features of gromacs 2018, it would save me some time. I'll generate some anyway, but I am using a very small subset of the features.

**Comment by jbarnoud** [comment]
Ready for review.
