### ISSUE TITLE
Couldn't import MDAnalysis module

### ISSUE THREAD

**Issue by Vedasheersh** [MDAnalysis/mdanalysis#1801]
### Expected behaviour
The module gets imported.

### Actual behaviour
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/__init__.py", line 182, in <module>
    from .lib import log
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/lib/__init__.py", line 38, in <module>
    from . import distances  # distances relies on mdamath
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/lib/distances.py", line 81, in <module>
    package="MDAnalysis.lib")
  File "/home/user/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/local/lib/python2.7/dist-packages/MDAnalysis/lib/c_distances.so: undefined symbol: PyFPE_jbuf

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) #This is not possible!
I am using the latest version. (installed using conda forge)

**Comment by orbeckst** [comment]
It looks to me that MDAnalysis was installed locally in `/usr/local/lib` (maybe using `pip`). If you have a MDAnalysis conda installation then it should live in your `/home/user/anaconda2` directory. I would remove `/usr/local/lib/python2.7/dist-packages/MDAnalysis` (try `pip uninstall MDAnalysis` outside conda; also try `pip uninstall MDAnalysisTests`).

Then check again.

**Comment by Vedasheersh** [comment]
@orbeckst Thank you for your comment. I tried removing MDAnalysis installed using pip. Now, I am able to import MDAnlaysis using conda environment.
