### ISSUE TITLE
Problem in RDF calculation

### ISSUE THREAD

**Issue by anirbanmandalrony1993** [MDAnalysis/mdanalysis#1891]
import MDAnalysis
from MDAnalysis import *
from MDAnalysis.analysis.rdf import InterRDF
u = MDAnalysis.Universe('Graphene_cyt_wat1.psf', 'template_prod_all.dcd')
c1 = u.select_atoms("resname CYT")
com1 = c1.center_of_mass()
c2 = u.select_atoms("resname CYT")
com2 =c2.center_of_mass()

rdf = InterRDF(com1, com2)
rdf.run()
plt.plot(rdf.rdf)
plt.show()

##################################################
Everything is fine in code except the rdf part which is giving the following error:
**Traceback (most recent call last):
  File "rdf_try.py", line 10, in <module>
    rdf = InterRDF(com1, com2)
  File "/home/iitgn/.local/lib/python2.7/site-packages/MDAnalysis/analysis/rdf.py", line 97, in __init__
    super(InterRDF, self).__init__(g1.universe.trajectory, **kwargs)
AttributeError: 'numpy.ndarray' object has no attribute 'universe'**_******

Please Help me out..!!

**Comment by anirbanmandalrony1993** [comment]
First of all thank you so much for the code that you provided me. I have tried the full code with both **fragments** and **groupby('resid')** but none of them helped me to get a proper plot that I am getting on vmd with only one selected atom..!! Can you please help me a bit more. In the psf file I have both bond information and also different segids for all 27 cytosine molecule..
```python
import MDAnalysis
import numpy as np
from MDAnalysis import *
from MDAnalysis.analysis.rdf import InterRDF
import matplotlib.pyplot as plt
MDAnalysis.core.flags['use_periodic_selections'] = True
MDAnalysis.core.flags['use_KDTree_routines'] = False

u = MDAnalysis.Universe('Graphene_cyt_wat1.psf', 'template_prod_all.dcd')

class BeadGroup(object):
    def __init__(self, groups):
        self._groups = groups

    def __len__(self):
        return len(self._groups)

    @property
    def positions(self):
        return np.array([g.center_of_mass() for g in self._groups], dtype=np.float32)

    @property
    def universe(self):
        return self._groups[0].universe

cyts = u.select_atoms('resname CYT')
#cyt_groups = cyts.fragments
cyt_groups1 = list(cyts.groupby('resids').values())

cyts = u.select_atoms('resname CYT')
#cyt_groups = cyts.fragments
cyt_groups2 = list(cyts.groupby('resids').values())

c1 = BeadGroup(cyt_groups1)
c2 = BeadGroup(cyt_groups2)

rdf = InterRDF(g1 = c1, g2 = c2, range = (0,15))
rdf.run()

plt.plot(rdf.bins,rdf.rdf)
plt.show()

```

![figure_1](https://user-images.githubusercontent.com/39052697/39758424-6f6b931c-52ed-11e8-8c6e-b7eb71342435.png)

**Comment by richardjgowers** [comment]
It looks like you might have to exclude the self contribution.  Try adding `InterRDF(...., exclusion_block=(1,1))`

**Comment by anirbanmandalrony1993** [comment]
Thank you soooooo much Sir.. It seems now I have got some fruitful result..!! Once again thank you Sir..
![figure_1](https://user-images.githubusercontent.com/39052697/39758935-e8dc862e-52ee-11e8-885a-55af810b88d9.png)

**Comment by orbeckst** [comment]
@omkantnirala Please ask questions on the mailing list https://groups.google.com/forum/#!forum/mdnalysis-discussion – for the last year or so we have been using the issue tracker exclusively for bug reports and feature discussions. In your email to the group please include a link to an issue if this important for context. However, most people don't have the time to follow links so you have a better chance of getting a response if your email is self contained and easy to understand.

**Comment by orbeckst** [comment]
FYI: alternatively use on-the-fly transformations https://gist.github.com/orbeckst/b611626e7640f399580e233195c6429c

(I couldn't get the `BeadGroup` to work.)
