### ISSUE TITLE
Problem with loading XTC offsets in parallel

### ISSUE THREAD

**Issue by mkhoshle** [MDAnalysis/mdanalysis#1988]
Hi MDAnalysis Developers,

I have an MPI job where I have 48 trajectory segments in the XTC format (newtraj_0.xtc,...newtraj_47.xtc). In order to have 48 segments one can just use a small size xtc file and copy this single segment 48 times to get a list of segments. I did not put all the segments in the repository because the whole size was large (30 GB). I repeat my job several times to collect statistics.
In my MPI job I use 48 processes and each process tries to copy one of the segments (e.g. newtraj_6.xtc for rank ID 6) to another folder. This copying is to avoid each effects. After each rank finish copying, it creates an index file for its own segment by doing print(len(mda.Universe(PSF, newtraj_rankID.xtc).trajectory)). I have a barrier to synchronize all processes.

**Expected behavior**
What I expect to see from my code is that each rank should create its index file and they should be able to successfully use the chain-reader to create the universe. 
Note:
This error happens when I test my code on more than one node. On a single workstation (node), it works fine. The index files are being written independently by each rank. So there should not be any overlap and I also tested the code with rank0 only creating the indices. However, it does not work either. The offset files cannot be corrupted except having a race condition. Is there any method in MDAnalysis like creating the universe, getting n_frames, etc that lead to rewriting the index file?

**Actual behavior**
Some ranks fail due to the following error:
```
Traceback (most recent call last):
  File "/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/main1-ga4py-updated-rmsd-chain-reader.py", line 73, in <module>
    u = mda.Universe(PSF, XTCs)
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/core/universe.py", line 305, in __init__
    self.load_new(coordinatefile, **kwargs)
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/core/universe.py", line 535, in load_new
    self.trajectory = reader(filename, **kwargs)
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/coordinates/chain.py", line 123, in __init__
    for filename in self.filenames]
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/coordinates/core.py", line 83, in reader
    return Reader(filename, **kwargs)
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 144, in __init__
    self._load_offsets()
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 183, in _load_offsets
    data = read_numpy_offsets(fname)
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 84, in read_numpy_offsets
    return {k: v for k, v in six.iteritems(np.load(filename))}
  File "/home/mkhoshle/miniconda2/envs/ga4py/lib/python2.7/site-packages/numpy/lib/npyio.py", line 429, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file '/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/files/.newtraj_41_1.xtc_offsets.npz' as a pickle
```

**Code to reproduce the behavior**
Here is the simple code to reproduce the problem:
```
import numpy as np
import MDAnalysis as mda
from shutil import copyfile
import glob, os
import mpi4py
from mpi4py import MPI

MPI.Init
comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

j = 1    # j is the repeat number
PSF = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/adk4AKE.psf')))
longXTC = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'traj_data_{}'.format(size),'newtraj_{}.xtc'.format(rank))))
longXTC1 = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/newtraj_{}_{}.xtc'.format(rank,j))))

copyfile(longXTC, longXTC1)
print(len(mda.Universe(PSF, longXTC1).trajectory))

comm.Barrier()
XTCs = glob.glob(os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/*.xtc'))))
u = mda.Universe(PSF, XTCs)

MPI.Finalize
```
Aby feedback and comment will be appreciated.

**Currently version of MDAnalysis**

- Which version are you using? (0.17.0)
- Which version of Python (Happens with both Python 2 & 3)
- Which operating system? (CentOS release 6.7)

**Comment by jbarnoud** [comment]
Thank you for reporting the issue. Out of curiosity, can you open the offset files directly with `numpy.load` without MPI. If you can, can you open the trajectories in MDAnalysis without MPI? Things should not fail like that, but we need to know how much is due to MPI, and at what point do things stop working.

**Comment by richardjgowers** [comment]
FWIW we also see the above error intermittently on Travis (1 in 50? runs) which also is also a (slightly) parallel environment.

This are the relevant lines in numpy for loading the npz file: 
https://github.com/numpy/numpy/blob/master/numpy/lib/npyio.py#L412

It looks like it's first failing to recognise the file as a zip file then failing to use it as a pickle.

**Comment by mkhoshle** [comment]
@jbarnoud Yes I am able to load the offsets even in parallel. As I mentioned in my issue report all the processes are able to load all the the offsets. Therefore, all of them are able to do the following:
```
offsets_ = []
offsets = glob.glob(os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/.*.xtc_offsets.npz'))))
for offset in offsets:
    offsets_.append(mda.coordinates.XDR.read_numpy_offsets(offset))
```
However, I am not sure what happens when they try to create the universe (i.e. `u = mda.Universe(PSF, XTCs)`) and some of the processes fail with the error above. Yes, serially one process can do `u = mda.Universe(PSF, XTCs)` and it does not fail. The error happens exactly at `return {k: v for k, v in six.iteritems(np.load(filename))}` at `read_numpy_offsets` in `XDR.py`. I tried to run this in a simple test case without using MDAnalysis at all. The error happens when I do it in parallel and as a result I think it is not MDAnalysis error. It does not seem to be numpy error either. Do you know why the file name start with `.`? It might be due to the way these files are being handled.
But I have no idea what should I do to avoid this error!!!

**Comment by mkhoshle** [comment]
@richardjgowers Does not seem to be a numpy problem. It should be something with XTC I think.

**Comment by orbeckst** [comment]
Did I understand you correctly in https://github.com/MDAnalysis/mdanalysis/issues/1988#issuecomment-405470107 that the line
https://github.com/MDAnalysis/mdanalysis/blob/5f151b48525a5d1d3d00b73855dbf6fe88960b69/package/MDAnalysis/coordinates/XDR.py#L84

fails when using MDAnalysi and that if you use only the line
```python
offset_dict = {k: v for k, v in six.iteritems(np.load(filename))}
```
in parallel (under mpi4py, without using any MDAnalysis) then it fails, too? In this case, is `filename` the same or different for the different MPI ranks?

**Comment by orbeckst** [comment]
>  Do you know why the file name start with `.`?

Offset files are named with a leading period to make them [hidden files](https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory) under Unix-like operating systems. I don't think that these files are treated in any other way by the OS except that `ls` does not show them by default.

**Comment by mkhoshle** [comment]
Yes, not just that line. Here is the code I use outside MDAnalysis.
```
def read_numpy_offsets(filename):
    return {k: v for k, v in six.iteritems(np.load(filename))}

def _load_offsets(filename):
    fname = filename

    if not isfile(fname):
       ctime = getctime(filename)
       size = getsize(filename)
       try:
          np.savez(filename,
          offsets=offsets, size=size, ctime=ctime,
                         n_atoms=data["n_atoms"])
       except Exception as e:
           print('111')
           print("Couldn't save offsets because: {}".format(e))

    data = read_numpy_offsets(fname)
    ctime_ok = size_ok = n_atoms_ok = False

    try:
       ctime_ok = getctime(filename) == data['ctime']
       size_ok = getsize(filename) == data['size']
       n_atoms_ok = data['n_atoms']
    except KeyError:
       pass

    if not (ctime_ok and size_ok and n_atoms_ok):
       print("Reload offsets from trajectory\n "
                          "ctime or size or n_atoms did not match")
       ctime = getctime(filename)
       size = getsize(filename)
       try:
          print('rank {}'.format(rank))
          np.savez(filename,
          offsets=offsets, size=size, ctime=ctime,
                         n_atoms=data["n_atoms"])
       except Exception as e:
             print("Couldn't save offsets because: {}".format(e))
    
PSF = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/adk4AKE.psf')))
longXTC = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'traj_data_{}'.format(size),'newtraj_{}.xtc'.format(rank))))
longXTC1 = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/newtraj_{}_{}.xtc'.format(rank,j))))

copyfile(longXTC, longXTC1)
print(len(mda.Universe(PSF, longXTC1).trajectory))

comm.Barrier()
offsets = glob.glob(os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/.*.xtc_offsets.npz'))))

for i in range(len(offsets)):
    fname = offsets[i]
    _load_offsets(fname)

MPI.Finalize
```
The error happens here:
```
Traceback (most recent call last):
  File "/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/test.py", line 87, in <module>
    _load_offsets(fname)
  File "/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/test.py", line 40, in _load_offsets
    data = read_numpy_offsets(fname)
  File "/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/test.py", line 24, in read_numpy_offsets
    return {k: v for k, v in six.iteritems(np.load(filename))}
  File "/home/mkhoshle/miniconda3/envs/py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '/oasis/scratch/comet/mkhoshle/temp_project/MPI-traj-split/files/.newtraj_10_1.xtc_offsets.npz' as a pickle
```
 and when I comment this part in my code, the error does not happen at all, but it happens when I do not comment it out.
```
try:
       ctime_ok = getctime(filename) == data['ctime']
       size_ok = getsize(filename) == data['size']
       n_atoms_ok = data['n_atoms']
    except KeyError:
       pass

    if not (ctime_ok and size_ok and n_atoms_ok):
       print("Reload offsets from trajectory\n "
                          "ctime or size or n_atoms did not match")
       ctime = getctime(filename)
       size = getsize(filename)
       try:
          print('rank {}'.format(rank))
          np.savez(filename,
          offsets=offsets, size=size, ctime=ctime,
                         n_atoms=data["n_atoms"])
       except Exception as e:
             print("Couldn't save offsets because: {}".format(e))
```

I believe this specific line is responsible for the error:
`np.savez(filename,offsets=offsets, size=size, ctime=ctime,n_atoms=data["n_atoms"])`

What happens if we remove this line? What does it do?

**Comment by kain88-de** [comment]
Oh yeah if multiple processes want to access the same file you are prone to race conditions. I thought your code is written so that each process has it's own file.

**Comment by mkhoshle** [comment]
Each process creates the offset file for one segment and there is a barrier to avoid race condition. But after the offset is written when I use chain-reader then each process wants to access all segments and if the condition `if not (ctime_ok and size_ok and n_atoms_ok):` is true then it means that several processes can write to the offset file at the same time.

**Comment by mkhoshle** [comment]
When I do not use chain-reader and each segment is assigned to one process only then there is no problem and no race condition.

**Comment by kain88-de** [comment]
so you have the following order to avoid race conditions and for some reason after the barrier, the offsets have changed?

1. generate offset files
1. sync barrier
1. read offset files

This shouldn't happen reading from multiple sources is fine. Do we touch the offset files when reading?

**Comment by mkhoshle** [comment]
Yes, I have this order. 
After the offsets are created you touch the offset files again in `XDR.py` inside `_read_offsets(self, store=False)` function. This happens because the condition `if not (ctime_ok and size_ok and n_atoms_ok):` gets satisfied:

```
def _read_offsets(self, store=False):
        """read frame offsets from trajectory"""
        offsets = self._xdr.offsets
        if store:
            ctime = getctime(self.filename)
            size = getsize(self.filename)
            try:
                np.savez(offsets_filename(self.filename),
                         offsets=offsets, size=size, ctime=ctime,
                         n_atoms=self._xdr.n_atoms)
            except Exception as e:
                warnings.warn("Couldn't save offsets because: {}".format(e))

if not (ctime_ok and size_ok and n_atoms_ok):
            warnings.warn("Reload offsets from trajectory\n "
                          "ctime or size or n_atoms did not match")
            self._read_offsets(store=True)
```

**Comment by kain88-de** [comment]
can you add print statements in your code so that we know which one of the three conditions is triggered?

**Comment by mkhoshle** [comment]
Yes, I printed everything. I did not put the output of my code because I run with 48 processes and it is large, But here I have shown with comments what happens exactly. Does this make sense now?
```
def _read_offsets(self, store=False):
        """read frame offsets from trajectory"""
        offsets = self._xdr.offsets
         ###################
        if store:   # This condition is triggered because store is True
         ###################
            ctime = getctime(self.filename)
            size = getsize(self.filename)
            try:
                ###################
                print('Step 2')
                ###################
                np.savez(offsets_filename(self.filename),
                         offsets=offsets, size=size, ctime=ctime,
                         n_atoms=self._xdr.n_atoms)
            except Exception as e:
                warnings.warn("Couldn't save offsets because: {}".format(e))

def _load_offsets(self):
        """load frame offsets from file, reread them from the trajectory if that
        fails"""
        fname = offsets_filename(self.filename)

        if not isfile(fname):
            self._read_offsets(store=True)
            return

        data = read_numpy_offsets(fname)
        ctime_ok = size_ok = n_atoms_ok = False

        try:
            ctime_ok = getctime(self.filename) == data['ctime']
            size_ok = getsize(self.filename) == data['size']
            n_atoms_ok = self._xdr.n_atoms == data['n_atoms']
        except KeyError:
            # we tripped over some old offset formated file
            pass

##### For some of the processes this condition is triggered:
        if not (ctime_ok and size_ok and n_atoms_ok):
            ###################
            print('Step 1')
            ###################
            warnings.warn("Reload offsets from trajectory\n "
                          "ctime or size or n_atoms did not match")
            ###################
            #    Here the _read_offsets is called with store=True 
            ###################
            self._read_offsets(store=True)  
        else:
            self._xdr.set_offsets(data['offsets'])
```

**Comment by kain88-de** [comment]
This doesn't help me. I would like to know the values of `ctime_ok`, `size_ok` and `n_atoms_ok`.  The only thing that could change would be the `ctime_ok` variable. But it would have changed *before* you call `_read_offsets(store=True)` again, in other words between your step 2 and 3. I do understand that in step 3 your try to write again and have a race condition.

**Comment by orbeckst** [comment]
@mkhoshle you can zip output and attach it to an issue.

**Comment by jbarnoud** [comment]
@mkhoshle Or post it as a gist so we do not have to download and unzip.

**Comment by mkhoshle** [comment]
Ok here is the link of the [output](https://gist.github.com/mkhoshle/a16a1704b082fbbafc051bf31dc420df). I run it with 48 processes and you can see that sometimes ctime_ok is `False` and that is going to cause problem.

**Comment by kain88-de** [comment]
OK thank you for the update. Your solution is only a band aid to me. It doesn't fix the race condition that happens elsewhere.

Your problem is that the trajectory file (the XTC) changes time stamps.  Your [example code](https://github.com/MDAnalysis/mdanalysis/issues/1988#issuecomment-405810499) doesn't show us where the timestamp change happens. It also doesn't test the situation we have in the XDR code. You check the timestamp of the offset file while the XDR code checks the timestamp of the XTC file. Can you share the code that generates the XTC files and the first round of offset files? I'm wondering why the timestamp changes

You can also try to run `find . -name "*offsets.npz -delete" to remove any offset files before you load the chain reader again. This will be the hammer solution to your problem, likely bad for performance though.

**Comment by mkhoshle** [comment]
Ok, I am nor really familiar with what is going on in the XTC file or offset file. Let me double check and I will update you!

**Comment by orbeckst** [comment]
Is it possible that `getctime(self.filename)` https://github.com/MDAnalysis/mdanalysis/blob/461aadf6733d234e0913bae774a6312a208ede27/package/MDAnalysis/coordinates/XDR.py#L187 is problematic because different ranks on *different nodes* might see a slightly different time??

Can you check (without using MDAnalysis) what `getctime(XTC)` and `getctime(INDEXFILE)` report for each rank for
- 24 ranks on a single node
- 48 ranks on two nodes?

**Comment by kain88-de** [comment]
The variable `self.filename` in the code has the relative path to the XDR file you are using. This is the timestamp that doesn't match up with our timestamp in the offset file. I do not know why those files would be touched again to be honest. 

Can you record the ctime of the XTC files before and after your synchronization points? Similar to what @orbeckst proposed.

**Comment by mkhoshle** [comment]
Here is the code that creates the XTC segments from a single XTC file:
```
#!/usr/bin/env python
import numpy as np
import MDAnalysis as mda
import time
import glob, os
from MDAnalysis import Writer
import mpi4py
from mpi4py import MPI

MPI.Init

comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()

PSF = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'files/adk4AKE.psf')))
XTC = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(),'newtraj.xtc')))

u = mda.Universe(PSF, XTC)

bsize = int(np.ceil(u.trajectory.n_frames/float(size)))
frames_seg = np.zeros([size,2], dtype=int)
for iblock in range(size):
    frames_seg[iblock, :] = iblock*bsize, (iblock+1)*bsize

d = dict([key, frames_seg[key]] for key in range(size))

start, stop = d[rank][0], d[rank][1]
step = 1

XTC_seg = os.path.abspath(os.path.normpath(os.path.join(os.getcwd(), "traj_{}".format(size),"newtraj_{}.xtc".format(rank))))

start1 = time.time()
with mda.Writer(XTC_seg) as out:
    for iframe, ts in enumerate(u.trajectory[start:stop:step]):
        out.write(ts)

start2 = time.time()

print("{} for rank {}".format(start2-start1,rank))

MPI.Finalize
```
And [here](https://github.com/MDAnalysis/mdanalysis/issues/1988#issue-341281036) is the way I create the offset file by doing `print(len(mda.Universe(PSF, longXTC1).trajectory))`. As I mentioned previously when I want to use chain-reader I create the offset files and that significantly reduces the time for opening the trajectory. With `refresh_offsets=True` the time for opening the trajectory is 120 S per rank. This kills the performance. With my current solution, chain-reader does not fail anymore and the time for opening the trajectory is 5S max.

**Comment by mkhoshle** [comment]
@kain88-de  Can you tell me what are these flags `ctime_ok,size_ok,n_atoms_ok` for? Why they matter and why they should match?
[Here](https://gist.github.com/mkhoshle/a16a1704b082fbbafc051bf31dc420df.js) is the link to the output you asked. I remember most of the time when doing the benchmarks I was getting this warning `ctime or size or n_atoms did not match
  warnings.warn("Reload offsets from trajectory\n "`.  What is the purpose of these checks in `XDR.py`?

**Comment by kain88-de** [comment]
- ctime checks the timestamp of the xdr file.
- size is the number of bytes in the file
- n_atoms is the number of atoms

We check all three to ensure the file hasn't changed and our stored offsets
are still valid. On your machine the timestamp stored in the offset file
doesn't match the timestamp of the actual file. You can see the timestamp
then you run `ls -l` in the folder with the xdr files. I hope that helps
you do  understand the XDR code.

**Comment by richardjgowers** [comment]
So one solution, is there any way of checking that we're inside an mpi process? Then we can put slave processes (ie not rank 0) into a waiting pattern of sleeping until it sees the offsets file, and rank 0 is the only one allowed to build offsets.  This is making assumptions that rank 0 is doing an identical work to all other ranks though.  If instead mpi was parallelised over files (ie rank 0 gets file_x, rank 1 file_y) then this would cause other ranks to hang.....

A different option is maybe putting down a "lock file" to indicate that offsets are in the process of being built, so other people should adopt a holding pattern and wait for the file. (with checks saying if the lock file is over 1h old, ignore it?)
