### ISSUE TITLE
Consistency: AtomGroup.residues = 0 ResidueGroup, further .atoms leads to ValueError

### ISSUE THREAD

**Issue by bieniekmateusz** [MDAnalysis/mdanalysis#1999]
**Expected behavior**

```python
sel.select_atoms('resname SOL')
Out[3]: <AtomGroup with 0 atoms>
sel.select_atoms('resname SOL').residues
Out[4]: <ResidueGroup with 0 residues>
sel.select_atoms('resname SOL').residues.atoms
```
This should return again:<AtomGroup with 0 atoms>

**Actual behavior**
Unclear error: 
```python
ValueError: need at least one array to concatenate

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6c6c6b22c39a>", line 1, in <module>
    sel.select_atoms('resname SOL').residues.atoms
  File "/home/dresio/software/virtualenvs/charm-mda/lib/python2.7/site-packages/MDAnalysis/core/groups.py", line 2340, in atoms
    return self.universe.atoms[np.concatenate(self.indices)]
ValueError: need at least one array to concatenate
```
**Code to reproduce the behavior**
``` 
u.select_atoms('resname NONE').residues.atoms
```

MDAnalysis 0.18.0

**Comment by richardjgowers** [comment]
@bieniekmateusz thanks for the bug find!  It looks like it needs a try/except around the concatenate call to recover from the `ValueError` of an empty residue.  I'm a little surprised `.residues` on an empty `AtomGroup` didn't fail first tbh.
