### ISSUE TITLE
Install fails with cython 0.26

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#2057]
**Expected behavior**

`pip install -e package` installs MDAnalysis.

**Actual behavior**

Install fails due to the following error during cython compilation:

```
pip install -e package/
Obtaining file:///home/jon/dev/mdanalysis/package
    Complete output from command python setup.py egg_info:
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
            cdef ns_int i, beadid_i, beadid_j
            cdef ns_int idx, nsearch
            cdef real dist2, dist
    
            nsearch = len(self.searchcoords)
                        ^
    ------------------------------------------------------------
    
    MDAnalysis/lib/nsgrid.pyx:420:21: Calling gil-requiring function not allowed without gil
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
            cdef ns_int i, beadid_i, beadid_j
            cdef ns_int idx, nsearch
            cdef real dist2, dist
    
            nsearch = len(self.searchcoords)
                             ^
    ------------------------------------------------------------
    
    MDAnalysis/lib/nsgrid.pyx:420:26: Converting to Python object not allowed without gil
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jon/dev/mdanalysis/package/setup.py", line 512, in <module>
        exts, cythonfiles = extensions(config)
      File "/home/jon/dev/mdanalysis/package/setup.py", line 396, in extensions
        extensions = cythonize(pre_exts)
      File "/home/jon/local/anaconda3/envs/apricot/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1016, in cythonize
        cythonize_one(*args)
      File "/home/jon/local/anaconda3/envs/apricot/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1138, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: MDAnalysis/lib/nsgrid.pyx
    Attempting to autodetect OpenMP support... Compiler supports OpenMP
    Will attempt to use Cython.
    Compiling MDAnalysis/lib/qcprot.pyx because it changed.
    Compiling MDAnalysis/lib/nsgrid.pyx because it changed.
    [1/2] Cythonizing MDAnalysis/lib/nsgrid.pyx
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/jon/dev/mdanalysis/package/
```

I am using cython 0.26 and commit d73b653f1 from the develop branch of MDAnalysis.
`python -c 'import cython; print(cython.__version__)'`
0.26

It works with cython>=0.27, though. We may just have to bump the minimum cython version.

**Comment by kain88-de** [comment]
what data type is the variable on which we call __len__?
