### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2186]
**Expected behavior**
I'm trying to compile the latest version of MDA, which has compiled successfully. However, an error occurred when I tried to import it. However, if I imported it again after the first failure, it works.

**Actual behavior**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Documents/GitHub/mdanalysis/package/MDAnalysis/__init__.py", line 200, in <module>
    from .coordinates.core import writer as Writer
  File "~/Documents/GitHub/mdanalysis/package/MDAnalysis/coordinates/__init__.py", line 737, in <module>
    from . import LAMMPS
  File "~/Documents/GitHub/mdanalysis/package/MDAnalysis/coordinates/LAMMPS.py", line 136, in <module>
    from ..topology.LAMMPSParser import DATAParser
  File "~/Documents/GitHub/mdanalysis/package/MDAnalysis/topology/__init__.py", line 305, in <module>
    from . import GSDParser
  File "~/Documents/GitHub/mdanalysis/package/MDAnalysis/topology/GSDParser.py", line 59, in <module>
    import gsd.hoomd
  File "~/miniconda3/envs/py36_intel/lib/python3.6/site-packages/gsd/hoomd.py", line 25, in <module>
    from gsd import fl
  File "__init__.pxd", line 885, in init gsd.fl
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

**Code to reproduce the behavior**

``` python

conda create -n idp intelpython3_core python=3
conda activate idp
pip install -e package/
python
>>> import MDAnalysis as mda
```
It works fine if I do this
```python
try:
    import MDAnalysis as mda
except:
    import MDAnalysis as mda
```
**Currently version of MDAnalysis**

- Which version are you using? 0.19.3-dev
- Which version of Python (`python -V`)? Python 3.6.5 :: Intel Corporation
- Which operating system? osx10.13.6

**Comment by xiki-tempula** [comment]
@richardjgowers I have tried but it doesn't seem to solve the problem.

**Comment by richardjgowers** [comment]
@xiki-tempula https://github.com/scipy/scipy/issues/3448 looks like it might be caused by a mixing of different numpy installations?  Try importing numpy and comparing where that module is compared to where you expect?

I couldn't reproduce this, but I also didn't use the intel python thing you seem to be using

**Comment by xiki-tempula** [comment]
Thank you for the help.
I got the same error with 
>>> from gsd import fl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "__init__.pxd", line 885, in init gsd.fl
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

My numpy version is 1.15.4 and I don't think I have two numpy in this env.

**Comment by richardjgowers** [comment]
@xiki-tempula this seems like a bug in gsd rather than MDA, so you might be best opening an issue with them here: https://bitbucket.org/glotzer/gsd/issues?status=new&status=open

If it stays problematic we can look at making gsd optional throughout and/or making a conda-forge package for gsd (which should sort out the numpy woes)
