### ISSUE TITLE
InterRDF fails Cannot allocate memory

### ISSUE THREAD

**Issue by dandalf02** [MDAnalysis/mdanalysis#2228]
**Expected behavior**

After constructing an rdf object with  'analysis.rdf.InterRDF(water, phosphates)' , the rdf.run() method calculates a radial distribution function for the given selection.   

Link to code, the tprfile and trajectories: https://drive.google.com/drive/folders/1xkLxC22OmcbbAS3h_15S-0gC3REJcx0Q?usp=sharing

**Actual behavior**

`rdf.run()` fails with either:  Segmentation Fault (core dumped); or with Cannot allocate memory. 

Traceback (most recent call last):
  File "hydr.py", line 45, in <module>
    rdf.run()
  File "/home/pyrus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/MDAnalysis/analysis/base.py", line 196, in run
    self._single_frame()
  File "/home/pyrus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/MDAnalysis/analysis/rdf.py", line 198, in _single_frame
    box=self.u.dimensions)
  File "/home/pyrus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/MDAnalysis/lib/distances.py", line 403, in capped_distance
    box=box, return_distances=return_distances)
  File "/home/pyrus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/MDAnalysis/lib/util.py", line 2042, in wrapper
    return func(*args, **kwargs)
  File "/home/pyrus/.pyenv/versions/3.7.1/lib/python3.7/site-packages/MDAnalysis/lib/distances.py", line 711, in _nsgrid_capped
    results = gridsearch.search(reference)
  File "MDAnalysis/lib/nsgrid.pyx", line 864, in MDAnalysis.lib.nsgrid.FastNS.search
  File "MDAnalysis/lib/nsgrid.pyx", line 680, in MDAnalysis.lib.nsgrid._NSGrid.fill_grid
MemoryError: Could not allocate memory for _NSGrid.beadids (1012660143712250400 bits requested)

Running through python debugger leads to the same result, points to a Cython nsgrid.pyx file. 

**Code to reproduce the behavior**
```python
import numpy as np
import MDAnalysis as mda
from MDAnalysis.analysis import rdf
u = mda.Universe('tprfile.tpr', 'trajectory_m.xtc')
phosphates = u.atoms.select_atoms('name O11 O12 O13 O14')
water = u.atoms.select_atoms('name OW')
rdf = mda.analysis.rdf.InterRDF(water, phosphates)
rdf.run()
```

**Current version of MDAnalysis**

- MDAnalysis version: 0.19.2
- Python version 3.7.1
- Operating system: Ubuntu 18.04.2 LTS

**Comment by orbeckst** [comment]
@dandalf02 can you try for yourself with the latest develop (see instructions under [Development Branch](https://github.com/MDAnalysis/mdanalysis/wiki/DevelopmentBranch). Let us know if the problem persists.

@ezavod thanks for checking.

**Comment by dandalf02** [comment]
@ezavod @orbeckst  Thanks a lot!  I have tried to run my code with the 0.19.3-dev version and I couldn't reproduce the problem anymore. Also, thanks for directing me to the #2132 :)

**Comment by orbeckst** [comment]
Glad that this had apparently been fixed. Open a new issue if the problem persists, please

**Comment by orbeckst** [comment]
Glad that this had apparently been fixed. Open a new issue if the problem persists, please
