### ISSUE TITLE
TST, CI: Appveyor Failure

### ISSUE THREAD

**Issue by tylerjereddy** [MDAnalysis/mdanalysis#2311]
@orbeckst Recently noted on the mailing list that Appveyor has started failing on PRs with [output similar](https://ci.appveyor.com/project/orbeckst/mdanalysis/builds/26436890) to that below the fold:

<details>

```
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\projects\mdanalysis\ci-helpers\appveyor\install-miniconda.ps1:42 char:18
+ if (! (Test-Path $env:RETRY_ERRORS)) {
+                  ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\projects\mdanalysis\ci-helpers\appveyor\install-miniconda.ps1:47 char:18
+ if (! (Test-Path $env:RETRY_MAX)) {
+                  ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand
 
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\projects\mdanalysis\ci-helpers\appveyor\install-miniconda.ps1:52 char:18
+ if (! (Test-Path $env:RETRY_DELAY)) {
+                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand
 
Installing miniconda latest for  bit architecture to C:\conda
Downloading Miniconda3-latest-Windows-x86_64.exe from https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe
File saved at C:\projects\mdanalysis\Miniconda3-latest-Windows-x86_64.exe
Installing C:\projects\mdanalysis\Miniconda3-latest-Windows-x86_64.exe to C:\conda
C:\projects\mdanalysis\Miniconda3-latest-Windows-x86_64.exe /InstallationType=AllUsers /S /AddToPath=1 /RegisterPython=1 /D=C:\conda
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName                                                                                                                                                                
-------  ------    -----      -----     ------     --  -- -----------                                                                                                                                                                
      8       3      928       1812       0.02   2960   1 Miniconda3-latest-Windows-x86_64                                                                                                                                           
Miniconda latest () installation complete
conda : Warning: 'defaults' already in 'channels' list, moving to the top
At C:\projects\mdanalysis\ci-helpers\appveyor\install-miniconda.ps1:246 char:1
+ conda config --add channels defaults
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Warning: 'defau...ving to the top:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Traceback (most recent call last):
  File "C:\conda\lib\site-packages\conda\exceptions.py", line 1062, in __call__
    return func(*args, **kwargs)
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\conda\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\conda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\conda\lib\site-packages\conda\cli\main_install.py", line 8, in <module>
    from .install import install
  File "C:\conda\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\conda\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\conda\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\conda\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\conda\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\conda\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\conda\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\conda\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\conda\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\conda\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\conda\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\conda\lib\site-packages\conda\exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\conda\lib\site-packages\conda\exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\conda\lib\site-packages\conda\exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\conda\lib\site-packages\conda\exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\conda\lib\site-packages\conda\exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\conda\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\conda\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\conda\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\conda\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "C:\conda\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "C:\conda\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\conda\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\conda\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\conda\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\conda\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
ERROR: the last command returned the following exit code: 1

```
</details>

This is most likely the issue reported upstream here: https://github.com/conda/conda/issues/8836

We may be well advised to apply a patch similar to [the one conda themselves applied to their appveyor CI](https://github.com/conda/conda/commit/44557fc90c02c95ea3fbd4b95e447c9d44b01303), though this may in fact be a matter to be handled upstream in ci-helpers, if I'm reading the error code correctly.

**Comment by orbeckst** [comment]
Other seemingly working quick fixes:
- https://github.com/geopandas/geopandas/pull/1029 
- https://github.com/drivendataorg/zamba/pull/70

**Comment by orbeckst** [comment]
Possibly related https://github.com/astropy/ci-helpers/issues/406

**Comment by orbeckst** [comment]
Btw, while we're at cleaning up the AppVeyor build: PR https://github.com/astropy/ci-helpers/pull/377 removed the outdated os image selection https://github.com/MDAnalysis/mdanalysis/blob/7449a38ebdaa80f7bf4df400df7855d83a5a7037/.appveyor.yml#L10-L11 because it lead to failures https://github.com/astropy/ci-helpers/issues/369
