### ISSUE TITLE
icodes not in PDBQTParser

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2361]
**Bug**

The PDBParser gives us `icode` TopologyAttrs but the PDBQTParser doesn't.

```python
>>> from MDAnalysis.tests.datafiles import *
>>> pdbqt = mda.Universe(PDBQT_input)
>>> pdb = mda.Universe(PDB)
>>> pdb.atoms.icodes
array(['', '', '', ..., '', '', ''], dtype=object)
>>> pdbqt.atoms.icodes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lily/anaconda3/envs/mdanalysis/lib/python3.7/site-packages/MDAnalysis/core/groups.py", line 2278, in __getattr__
    cls=self.__class__.__name__, attr=attr))
AttributeError: AtomGroup has no attribute icodes
```

**Suggested solution**
This is an excerpt from PDBQTParser.py:

```python
        resids = np.array(resids, dtype=np.int32)
        icodes = np.array(icodes, dtype=object)
        resnames = np.array(resnames, dtype=object)
        chainids = np.array(chainids, dtype=object)

        residx, (resids, icodes, resnames, chainids) = change_squash(
            (resids, icodes), (resids, icodes, resnames, chainids))
        n_residues = len(resids)
        attrs.append(Resids(resids))
        attrs.append(Resnums(resids.copy()))
        attrs.append(Resnames(resnames))
```

`icodes` are already parsed; they just need to be appended to `attrs`.

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.1
- Which version of Python (`python -V`)? 3.7.3
- Which operating system? MacOS Mojave

**Comment by lilyminium** [comment]
Also, XPDB does implement icodes, despite the documentation thinking it doesn't.

```python
>>> from MDAnalysis.tests.datafiles import XPDB_small
>>> xpdb = mda.Universe(XPDB_small, topology_format='XPDB')
>>> xpdb.atoms.icodes
array(['', '', '', '', ''], dtype=object)
>>> xpdb.kwargs
{'topology_format': 'XPDB'}
```
