### ISSUE TITLE
Integer atom types do not work as expected (TXYZ files)

### ISSUE THREAD

**Issue by mquevill** [MDAnalysis/mdanalysis#2435]
**Expected behavior**

When using `poltype` to automate the fitting of an AMOEBA force field with Tinker, the atom types are set to integer values (401, 402, etc.). When trying to read these files into MDAnalysis with the TXYZ reader, the atom type selections do not behave as one would normally expect.

**Actual behavior**

Selecting atoms becomes a strange process. Trying to select a certain type does not work. However, using a wildcard is able to select multiple integer types.

``` python
>>> u.select_atoms("type 419")
<AtomGroup with 0 atoms>
>>> list(u.atoms)[0]
<Atom 1: N of type 419 resid 1 and segid SYSTEM>
>>> u.select_atoms("type 4*")
<AtomGroup with 61 atoms>
```

In addition, trying to use a topology guesser (since MDAnalysis _doesn't read in the connectivity data_ from a TXYZ file) fails with integer types.

``` python
>>> mol = u.select_atoms("type 4*")
>>> mda.topology.guessers.guess_bonds(mol,mol.positions)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/MDAnalysis/topology/guessers.py", line 239, in guess_bonds
    ". These can be defined manually using the" +
TypeError: sequence item 0: expected str instance, int found
```

This error can easily be fixed by forcing a `str` in `guessers.py`:
``` diff
     # check that all types have a defined vdw
     if not all(val in vdwradii for val in set(atomtypes)):
         raise ValueError(("vdw radii for types: " +
-                           ", ".join([t for t in set(atomtypes) if
+                           ", ".join([str(t) for t in set(atomtypes) if
                                      not t in vdwradii]) +
                           ". These can be defined manually using the" +
                           " keyword 'vdwradii'"))
```
which gives the output:
``` python
>>> mol = u.select_atoms("type 4*")
>>> md.topology.guessers.guess_bonds(mol,mol.positions)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/michael/.local/lib/python3.6/site-packages/MDAnalysis/topology/guessers.py", line 240, in guess_bonds
    " keyword 'vdwradii'"))
ValueError: vdw radii for types: 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442. These can be defined manually using the keyword 'vdwradii'
```

The workaround for the `guess_bonds()` function is to set the types as their names to get approximate vdW radii.

``` python
>>> mol.types = mol.names
>>> mda.topology.guessers.guess_bonds(mol,mol.positions)
((0, 2), (0, 4), (0, 8), (1, 2), (1, 5), (1, 12), (2, 3), (4, 5), (4, 6), (5, 7), (8, 9), (8, 10), (8, 11), (12, 13), (12, 14), (12, 15), (13, 16), (13, 17), (13, 18), (16, 19), (16, 20), (16, 21), (19, 22), (19, 23), (19, 24), (22, 25), (22, 26), (22, 27), (25, 28), (25, 29), (25, 30), (28, 31), (28, 32), (28, 33), (31, 34), (31, 35), (31, 36), (34, 37), (34, 38), (34, 39), (37, 40), (37, 41), (37, 42), (40, 43), (40, 44), (40, 45), (43, 46), (43, 47), (43, 48), (46, 49), (46, 50), (46, 51), (49, 52), (49, 53), (49, 54), (52, 55), (52, 59), (52, 60), (55, 56), (55, 57), (55, 58))
```

**Code to reproduce the behavior**

Show us how to reproduce the failure. If you can, use trajectory files from the test data.

``` python
import MDAnalysis as mda

u = mda.Universe("single.arc")
print(u.select_atoms("type 419"))
print(list(u.atoms)[0])
print(u.select_atoms("type 4*"))

mda.topology.guessers.guess_bonds(u.atoms,u.atoms.positions)

u.atoms.types = u.atoms.names
mda.topology.guessers.guess_bonds(u.atoms,u.atoms.positions)
```

**Currently version of MDAnalysis**

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) **0.20.1**
- Which version of Python (`python -V`)? **Python 3.6.9**
- Which operating system? **Linux Mint 19.3, kernel 5.0.0-37**

**Example file needed for testing**

Please rename as "single.arc": [single.txt](https://github.com/MDAnalysis/mdanalysis/files/4020260/single.txt)

**Comment by jbarnoud** [comment]
Thank you for the detailed report.
