### ISSUE TITLE
Can't write PDB if dimensions is None

### ISSUE THREAD

**Issue by jaimergp** [MDAnalysis/mdanalysis#2679]
## Expected behavior ##

I am using `mda.Universe` objects to handle multiformat IO in one project. A common workflow involves ingesting PDB IDs and writing PDBs to disk.

## Actual behavior ##

I have found at least one PDB ID that makes this simple process fail with this error:

```
Traceback (most recent call last):
  File "mda_bug.py", line 7, in <module>
    m.atoms.write("2bbm.pdb")
  File "/home/jaime/.conda/envs/structuralalignment/lib/python3.8/site-packages/MDAnalysis/core/groups.py", line 3123, in write
    w.write(self.atoms)
  File "/home/jaime/.conda/envs/structuralalignment/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py", line 763, in write
    self._write_pdb_header()
  File "/home/jaime/.conda/envs/structuralalignment/lib/python3.8/site-packages/MDAnalysis/coordinates/PDB.py", line 641, in _write_pdb_header
    self.CRYST1(self.convert_dimensions_to_unitcell(u.trajectory.ts))
  File "/home/jaime/.conda/envs/structuralalignment/lib/python3.8/site-packages/MDAnalysis/coordinates/base.py", line 2150, in convert_dimensions_to_unitcell
    lengths, angles = ts.dimensions[:3], ts.dimensions[3:]
TypeError: 'NoneType' object is not subscriptable
```

## Code to reproduce the behavior ##

``` python
from MDAnalysis import fetch_mmtf
m = fetch_mmtf("2BBM")
m.atoms.write("2bbm.pdb")

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.20.1

- Which version of Python (`python -V`)?
3.8.2

- Which operating system?
Ubuntu on WSL

**Comment by richardjgowers** [comment]
thanks @jaimergp .  As a workaround for now...
```python
if u.dimensions is None:
    u.trajectory.ts._unitcell = np.zeros(6) 
```
 but yeah the Writer shouldn't be failing like this.

**Comment by jaimergp** [comment]
Thanks!
