### ISSUE TITLE
MDAnalysis not compatible with Biopython 1.78

### ISSUE THREAD

**Issue by nadzhou** [MDAnalysis/mdanalysis#3050]
Because Biopython has updated from 1.77 to 1.78 they have removed the Bio.Alphabet library which MDAnalysis uses, now we just get an error of Bio.Alphabet has been removed. 

Please fix this bug since the whole MDAnalysis package is built on this.

**Comment by IAlibay** [comment]
@nadzhou Could you give us more details, i.e. which version of MDAnalysis are you using, is this a clean install or are you using things like parmed (which I believe also uses bio.alphabet)?

@RMeli wasn't this something that was fixed in #2457?

**Comment by nadzhou** [comment]
@IAlibay i just installed the library from conda the standard way. 


i've been using this module for the past 3 weeks now and haven't seen any bug fixes.

**Comment by IAlibay** [comment]
@nadzhou can you confirm what you get when you do:

```
import MDAnalysis as mda
print(mda.__version)
```

Also can you paste the full error here please?

**Comment by nadzhou** [comment]
@IAlibay you'll have to give me some time. my laptop is stuck rn.

**Comment by nadzhou** [comment]
@IAlibay, here's my specifications: 
	> Python==3.6
	> MDAnalysis==0.20.1
	> Biopython==1.78

Here's the error code: 

	Traceback (most recent call last):
	  File "xtc_read.py", line 2, in <module>
	    import MDAnalysis as mda
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/__init__.py", line 184, in <module>
	    from .lib import log
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/lib/__init__.py", line 40, in <module>
	    from . import NeighborSearch
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/lib/NeighborSearch.py", line 37, in <module>
	    from MDAnalysis.core.groups import AtomGroup, Atom
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/core/__init__.py", line 465, in <module>
	    from . import AtomGroup
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/core/AtomGroup.py", line 28, in <module>
	    from . import universe
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/core/universe.py", line 128, in <module>
	    from .topology import Topology
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/core/topology.py", line 64, in <module>
	    from .topologyattrs import Atomindices, Resindices, Segindices
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/MDAnalysis/core/topologyattrs.py", line 40, in <module>
	    import Bio.Alphabet
	  File "/home/nadzhou/anaconda3/envs/md_navid/lib/python3.6/site-packages/Bio/Alphabet/__init__.py", line 21, in <module>
	    "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
	ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

tell me if you need anything else.

**Comment by nadzhou** [comment]
Update. I found the problem: conda isn't installing the latest MDAnalysis version because that's what I'd used to install the module.

**Comment by lilyminium** [comment]
@nadzhou Try updating mdanalysis to 1.0.0 with ``conda update mdanalysis`` or ``conda install -c conda-forge mdanalysis==1.0.0``, which has the #2457 fix. Does that fix it for you?

**Comment by nadzhou** [comment]
@lilyminium yup it does. let me mark this as fixed.

**Comment by lilyminium** [comment]
Great, I'll close the issue :-)
