### ISSUE TITLE
[1.0.1 pre-release issues] python 3.7 linux doesn't like our setup file

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/mdanalysis#3110]
## Expected behavior ##

`pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple MDAnalysis==1.0.2b0`

_should_ work on all python versions supported by 1.0.1 (2.7, 3.5, 3.6, 3.7, 3.8).

_Note: 1.0.2b is only for the benefit of testpypi because our testpypi 1.0.1 was broken and you can't overwrite version numbers (it's all very silly)._

## Actual behavior ##

For python 3.8 we fail with the following trace (as contributed by @lilyminium):

```
(empty-mda37-102b) lily@gavle:~/pydev/mdanalysis$ pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple MDAnalysis==1.0.2b
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting MDAnalysis==1.0.2b
  Downloading https://test-files.pythonhosted.org/packages/0b/bf/2d76560d1316e8f6e2a2c94a33a91ee680383f852f714d2674b1a1702c8d/MDAnalysis-1.0.2b0.tar.gz (3.8 MB)
     |████████████████████████████████| 3.8 MB 4.7 MB/s
    ERROR: Command errored out with exit status 1:
     command: /store/opt/anaconda3/envs/empty-mda37-102b/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6ybglwm5/mdanalysis_9e45fff416244f4fa352fa475506fab1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6ybglwm5/mdanalysis_9e45fff416244f4fa352fa475506fab1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8erpwm17
         cwd: /tmp/pip-install-6ybglwm5/mdanalysis_9e45fff416244f4fa352fa475506fab1/
    Complete output (31 lines):
    /tmp/pip-install-6ybglwm5/mdanalysis_9e45fff416244f4fa352fa475506fab1/setup.py:131: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
      self.config = configparser.SafeConfigParser()
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6ybglwm5/mdanalysis_9e45fff416244f4fa352fa475506fab1/setup.py", line 654, in <module>
        zip_safe=False,  # as a zipped egg the *.so files are not found (at
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/__init__.py", line 162, in setup
        _install_setup_requires(attrs)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/__init__.py", line 157, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/dist.py", line 702, in fetch_build_eggs
        replace_conflicting=True,
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
        replace_conflicting=replace_conflicting
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1064, in best_match
        return self.obtain(req, installer)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1076, in obtain
        return installer(requirement)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/dist.py", line 758, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/installer.py", line 133, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/wheel.py", line 99, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/wheel.py", line 107, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/store/opt/anaconda3/envs/empty-mda37-102b/lib/python3.7/site-packages/setuptools/wheel.py", line 128, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [Errno 17] File exists: '/tmp/pip-install-6ybglwm5/mdanalysis_9e45fff416244f4fa352fa475506fab1/.eggs/numpy-1.16.6-py3.7-linux-x86_64.egg'
    Attempting to autodetect OpenMP support... Compiler supports OpenMP
    Will not attempt to use Cython.
    ----------------------------------------
WARNING: Discarding https://test-files.pythonhosted.org/packages/0b/bf/2d76560d1316e8f6e2a2c94a33a91ee680383f852f714d2674b1a1702c8d/MDAnalysis-1.0.2b0.tar.gz#sha256=cb9d2609f5af980b7061c792be770b1ef3ae3b9edba2aac0c412a4644693b207 (from https://test.pypi.org/simple/mdanalysis/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3,!=3.4.*,<3.9). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement MDAnalysis==1.0.2b
ERROR: No matching distribution found for MDAnalysis==1.0.2b
```

Note that I get a slightly different failure:

```
(test-mda-3.7-2) ➜  ~ pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple MDAnalysis==1.0.2b0
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Collecting MDAnalysis==1.0.2b0
  Downloading https://test-files.pythonhosted.org/packages/0b/bf/2d76560d1316e8f6e2a2c94a33a91ee680383f852f714d2674b1a1702c8d/MDAnalysis-1.0.2b0.tar.gz (3.8 MB)
     |████████████████████████████████| 3.8 MB 2.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: /home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-cza2f6g5/mdanalysis_1797230d0d544d70a1678e5b2c3f4d4e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-cza2f6g5/mdanalysis_1797230d0d544d70a1678e5b2c3f4d4e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-va744iss
         cwd: /tmp/pip-install-cza2f6g5/mdanalysis_1797230d0d544d70a1678e5b2c3f4d4e/
    Complete output (31 lines):
    /tmp/pip-install-cza2f6g5/mdanalysis_1797230d0d544d70a1678e5b2c3f4d4e/setup.py:131: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
      self.config = configparser.SafeConfigParser()
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cza2f6g5/mdanalysis_1797230d0d544d70a1678e5b2c3f4d4e/setup.py", line 654, in <module>
        zip_safe=False,  # as a zipped egg the *.so files are not found (at
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/dist.py", line 689, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 768, in resolve
        replace_conflicting=replace_conflicting
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/dist.py", line 745, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/installer.py", line 80, in fetch_build_egg
        wheel.install_as_egg(dist_location)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/wheel.py", line 95, in install_as_egg
        self._install_as_egg(destination_eggdir, zf)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
        self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
      File "/home/bioc1523/software/anaconda/install/envs/test-mda-3.7-2/lib/python3.7/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
        os.mkdir(destination_eggdir)
    FileExistsError: [Errno 17] File exists: '/tmp/pip-install-cza2f6g5/mdanalysis_1797230d0d544d70a1678e5b2c3f4d4e/.eggs/numpy-1.16.6-py3.7-linux-x86_64.egg'
    Attempting to autodetect OpenMP support... Compiler supports OpenMP
    Will not attempt to use Cython.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Unrelated issue ##

I noticed `requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3,!=3.4.*,<3.9` that should really be `requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,<3.9`

## Current version of MDAnalysis ##

- Which version are you using? 1.0.1 testpypi
- Which version of Python (`python -V`)? 3.7.9
- Which operating system? Ubuntu 20.04 LTS (both for @lilyminium and I)

Any ideas @MDAnalysis/coredevs? It's another one of those that is hindering release. We both couldn't really work out what's going on.

**Comment by lilyminium** [comment]
Update: Also tested on Ubuntu 19.04 3.7.9 and Ubuntu 20.04 3.7.0, 3.7.1, and 3.7.8. Also of note: installation works fine on Mac OS Catalina with 3.7.9 and also numpy 1.16.6 . 

Possibly related: https://github.com/druid-io/pydruid/issues/198

So, focusing on ``numpy-1.16.6-py3.7-linux-x86_64.egg``... should numpy be restricted to a narrower range of versions? Should it be in both setup and install requires? Is it clashing with our dependencies somehow?

**Comment by nbgl** [comment]
The plot thickens: it works on Python 3.7.3 on my Raspberry Pi (Raspbian 10).

**Comment by lilyminium** [comment]
Update 2: if I install 'numpy>=1.13.3,<1.17' first, it works. If I do not specify these constraints, it installs 1.19.something and goes back to failing

**Comment by lilyminium** [comment]
Update 3: installing on Ubuntu 20.04 with `venv` on Python 3.7.4 also works! 🤔

**Comment by nbgl** [comment]
Related? https://bugs.python.org/issue29694

**Comment by IAlibay** [comment]
> Related? https://bugs.python.org/issue29694

Looking at the affected versions, wouldn't 3.5 and 3.6 fail if that was the case?

**Comment by lilyminium** [comment]
I think I may be wrong re: the other python versions I tested. @IAlibay, when was the Python build that you installed (the info listed when you just run `python`)? I just built another conda environment and for some reason this time the Python it installed was built on Dec 9 2020. In this environment, pip install works. In my old environment, conda installed a version built on Aug 31 2020. In these environments (replicated on Ubuntu 19.04 and 20.04), installing MDAnalysis consistently fails.

**Comment by IAlibay** [comment]
Ok I think I might have worked out why it suddenly started working for you @lilyminium 

Here's my 31st Dec build:

```
# packages in environment at /home/bioc1523/software/anaconda/install/envs/test-mda-3.7-3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
pip                       21.0               pyhd8ed1ab_0    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

If I just pip install on that it fails as normal.

However if I pip install numpy 1.16.6 first (before creating this environment, in an environment I've since deleted), it all works out. This is because the "right" numpy install is in cache so it just pulls from it. If I purge cache (using `pip cache purge`) then it starts failing to install again.

I'm tempted to go ahead and mark this as a `wontfix` since it seems like an issue with pip being unable to pull numpy? Thoughts?

**Comment by lilyminium** [comment]
Yeah I think you're right, @IAlibay. After purging the pip cache, neither conda nor virtualenv installs appear to be working on 3.7.9 or 3.7.4. However, it continues to work on MacOS Catalina on 3.7.9.

It is inconvenient to not support 3.7 on Ubuntu but I'm a bit lost here. :(

**Comment by IAlibay** [comment]
> Edit: we could maybe circumvent issues by getting people to install numpy first on 3.7.

I think that's going to have to be our approach for 1.0.1. It seems to be some obscure upstream issue and at least for now asking folks to pip install numpy first isn't a big ask compared to say limiting matplotlib versions.

**Comment by IAlibay** [comment]
Closing as wontfix - unless someone can think of something better, the solution is just to pip install numpy first if this occurs.
