### ISSUE TITLE
TPRParser does not support TPX version 122 from Gromacs 2021

### ISSUE THREAD

**Issue by hejamu** [MDAnalysis/mdanalysis#3180]
Hi everyone,

TPR files generated by Gromacs 2021 don't work with MDAnalysis. I tried just bumping the supported version numbers, but that didn't work either.

If I can be of any help, let me know.

## Expected behavior ##

The TPR parser reads topologies from TPR file produced by Gromacs 2021

## Actual behavior ##

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henrik/.local/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 372, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/home/henrik/.local/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 141, in _topology_from_file_like
    raise ValueError(
ValueError: Failed to construct topology from file tpi_run.tpr with parser <class 'MDAnalysis.topology.TPRParser.TPRParser'>.
Error: Your tpx version is 122, which this parser does not support, yet 
```

With bumping the supported versions to 122:

```
>>> import MDAnalysis as mda
>>> mda.Universe('tpi_run.tpr')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/mdanalysis/package/MDAnalysis/core/universe.py", line 334, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/tmp/mdanalysis/package/MDAnalysis/core/universe.py", line 120, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "/tmp/mdanalysis/package/MDAnalysis/topology/TPRParser.py", line 237, in parse
    tpr_top = tpr_utils.do_mtop(data, th.fver,
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 297, in do_mtop
    moltype = do_moltype(data, symtab, fver)
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 692, in do_moltype
    atoms_obj = do_atoms(data, symtab, fver)
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 785, in do_atoms
    atomnames = [symtab[i] for i in ndo_int(data, nr)]
  File "/tmp/mdanalysis/package/MDAnalysis/topology/tpr/utils.py", line 785, in <listcomp>
    atomnames = [symtab[i] for i in ndo_int(data, nr)]
IndexError: list index out of range
``` 

## Code to reproduce the behavior ##

```python
>>> import MDAnalysis as mda
>>> mda.Universe('tpi_run.tpr')
```

## Current version of MDAnalysis ##

```bash
$ python3 -c "import MDAnalysis as mda; print(mda.__version__)"
1.0.1
$ python3 -V
Python 3.8.5
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by IAlibay** [comment]
ccing @jbarnoud
