### ISSUE TITLE
Broken pickling

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#3309]
## Expected behavior ##

The user guide example on parallel analysis works. https://userguide.mdanalysis.org/stable/examples/analysis/custom_parallel_analysis.html#Other-possible-parallelism-approaches-for-multiple-analyses

## Actual behavior ##

The joblib part fails (https://userguide.mdanalysis.org/stable/examples/analysis/custom_parallel_analysis.html#Other-possible-parallelism-approaches-for-multiple-analyses)

#3233 / #3281 result in a RecursionError that displeases the serializer.

```python
from joblib import Parallel, delayed
import multiprocessing
num_cores = multiprocessing.cpu_count()
from MDAnalysis.analysis.base import AnalysisFromFunction

rog_1 = AnalysisFromFunction(radgyr, u.trajectory,
                           protein, protein.masses,
                           total_mass=np.sum(protein.masses))

rog_2 = AnalysisFromFunction(radgyr, u.trajectory,
                           protein, protein.masses,
                           total_mass=np.sum(protein.masses))

rog_3 = AnalysisFromFunction(radgyr, u.trajectory,
                           protein, protein.masses,
                           total_mass=np.sum(protein.masses))

rog_4 = AnalysisFromFunction(radgyr, u.trajectory,
                           protein, protein.masses,
                           total_mass=np.sum(protein.masses))

analysis_ensemble = [rog_1, rog_2, rog_3, rog_4]

def run_analysis(analysis):
    analysis.run()
    return analysis.results

results_ensemble = Parallel(n_jobs=num_cores)(delayed(run_analysis)(analysis)
                                                for analysis in analysis_ensemble)
```

results in the error trace:

```
  File "/Users/lily/anaconda3/envs/mda-dev/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
    if key in self.data:
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/analysis/base.py", line 110, in __getattr__
    return self[attr]
  File "/Users/lily/anaconda3/envs/mda-dev/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
    if key in self.data:
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/analysis/base.py", line 110, in __getattr__
    return self[attr]
  File "/Users/lily/anaconda3/envs/mda-dev/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
    if key in self.data:
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/analysis/base.py", line 110, in __getattr__
    return self[attr]
  File "/Users/lily/anaconda3/envs/mda-dev/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
    if key in self.data:
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/analysis/base.py", line 110, in __getattr__
    return self[attr]
  File "/Users/lily/anaconda3/envs/mda-dev/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
    if key in self.data:
  File "/Users/lily/pydev/mdanalysis/package/MDAnalysis/analysis/base.py", line 110, in __getattr__
    return self[attr]
  File "/Users/lily/anaconda3/envs/mda-dev/lib/python3.7/collections/__init__.py", line 1023, in __getitem__
    if key in self.data:
RecursionError: maximum recursion depth exceeded
"""

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-29-427dec8e84e0> in <module>
      1 results_ensemble = Parallel(n_jobs=num_cores)(delayed(run_analysis)(analysis)
----> 2                                                 for analysis in analysis_ensemble)

~/anaconda3/envs/mda-dev/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1040 
   1041             with self._backend.retrieval_context():
-> 1042                 self.retrieve()
   1043             # Make sure that we get a last message telling us we are done
   1044             elapsed_time = time.time() - self._start_time

~/anaconda3/envs/mda-dev/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    919             try:
    920                 if getattr(self._backend, 'supports_timeout', False):
--> 921                     self._output.extend(job.get(timeout=self.timeout))
    922                 else:
    923                     self._output.extend(job.get())

~/anaconda3/envs/mda-dev/lib/python3.7/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/anaconda3/envs/mda-dev/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

~/anaconda3/envs/mda-dev/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) Current develop
- Which version of Python (`python -V`)?
- Which operating system?

**Comment by orbeckst** [comment]
@yuxuanzhuang can you have a look, please?

**Comment by lilyminium** [comment]
@yuxuanzhuang feel free to tackle this if you like, but I don't think it's an issue with pickling and more with how the new `Results` checks keys in `__getitem__` -- it needs to ignore the "data" key. I bypassed this earlier by setting `data` in `__init__`, but I don't think pickling calls `__init__`. Perhaps you have ideas for a good test though? :)

**Comment by orbeckst** [comment]
Then that's the problem that @PicoCentauri mentioned in the PR on results: pickling Results does not work.

A test for being able to use multiprocessing would be good although in this case just testing pickling works seems sufficient.

**Comment by yuxuanzhuang** [comment]
The issue is during unpickling, a proper `__setattr__` (not `__setitem__`) needs to be called to handle the recursive loop well. A simple test would be
```
import pickle
from MDAnalysis.analysis.base import Results

result = Results(result=0)

result_p = pickle.dumps(result)
result_new = pickle.loads(result_p)
```
