### ISSUE TITLE
ReaderBase.__del__:  I/O operation on closed file

### ISSUE THREAD

**Issue by RMeli** [MDAnalysis/mdanalysis#3386]
## Expected behavior ##

I expect MDAnalysis to terminate without (ignored) exceptions.

## Actual behavior ##

When I create an universe from a PDB file defined as `StringIO`, I get the following error:
```
Exception ignored in: <function ReaderBase.__del__ at 0x7ff8d00a8dd0>
Traceback (most recent call last):
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2175, in __del__
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/coordinates/PDB.py", line 458, in close
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/lib/util.py", line 720, in close
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/lib/util.py", line 826, in flush
ValueError: I/O operation on closed file.
```

## Code to reproduce the behavior ##

``` python
from io import StringIO

import MDAnalysis as mda

print(mda.__version__)

res_str = """\
ATOM    659  N   THR A 315      22.716  15.055  -1.000  1.00 16.08         A N
ATOM    660  CA  THR A 315      22.888  13.803  -0.302  1.00 15.13         A C
ATOM    661  C   THR A 315      22.006  12.700  -0.882  1.00 15.69         A C
ATOM    662  O   THR A 315      21.138  12.959  -1.727  1.00 16.25         A O
ATOM    663  CB  THR A 315      22.481  13.956   1.182  1.00 16.22         A C
ATOM    664  CG2 THR A 315      22.874  15.310   1.747  1.00 17.32         A C
ATOM    665  OG1 THR A 315      21.047  13.922   1.304  1.00 15.14         A O
"""

res = mda.Universe(StringIO(res_str), format='PDB')
```

## Current version of MDAnalysis ##

- Which version are you using? `2.0.0-dev0`
- Which version of Python? `3.7.10`
- Which operating system? `macOS 11.5.1`

**Comment by orbeckst** [comment]
See in particular #2089 (possibly somewhat related  #1530, #1506, #1250).

**Comment by RMeli** [comment]
Thanks for pointing them out @orbeckst (I forgot to check closed issues...). However, using `NamedStream`s does not seem to solve the issue for me:
```python
from io import StringIO

import MDAnalysis as mda
from MDAnalysis.lib.util import NamedStream

print(mda.__version__)

res_str = """\
ATOM    659  N   THR A 315      22.716  15.055  -1.000  1.00 16.08         A N
ATOM    660  CA  THR A 315      22.888  13.803  -0.302  1.00 15.13         A C
ATOM    661  C   THR A 315      22.006  12.700  -0.882  1.00 15.69         A C
ATOM    662  O   THR A 315      21.138  12.959  -1.727  1.00 16.25         A O
ATOM    663  CB  THR A 315      22.481  13.956   1.182  1.00 16.22         A C
ATOM    664  CG2 THR A 315      22.874  15.310   1.747  1.00 17.32         A C
ATOM    665  OG1 THR A 315      21.047  13.922   1.304  1.00 15.14         A O
"""

res = mda.Universe(NamedStream(StringIO(res_str), "res.pdb"))
```
 
```
2.0.0-dev0
/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/lib/util.py:648: RuntimeWarning: Constructed NamedStream from a NamedStream
  RuntimeWarning)
Exception ignored in: <function ReaderBase.__del__ at 0x7fc010400e60>
Traceback (most recent call last):
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2175, in __del__
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/coordinates/PDB.py", line 458, in close
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/lib/util.py", line 720, in close
  File "/Users/rmeli/Documents/git/software/mdanalysis/package/MDAnalysis/lib/util.py", line 826, in flush
ValueError: I/O operation on closed file.
```

This was already reported in https://github.com/MDAnalysis/mdanalysis/issues/2089#issuecomment-481578337 .

**Comment by orbeckst** [comment]
Ok, so it’s really an issue. 

> Am 8/16/21 um 01:41 schrieb Rocco Meli ***@***.***>:
> 
> This was already reported in #2089 (comment) .

**Comment by IAlibay** [comment]
As per #3481 - this pops up quite often in the tests.

**Comment by IAlibay** [comment]
So there is a rather simple fix here, which is to change:

https://github.com/MDAnalysis/mdanalysis/blob/3322ab2b9cb4987306225a574dde6ce1bae51fab/package/MDAnalysis/lib/util.py#L728-L735

to:

```python
        if self.closed:
            return
        if self.close_stream or force:
            try:
                return self.stream.close()
            except AttributeError:
                return super(NamedStream, self).close()
        else:
            self.flush()
            self.reset()
```

avoiding an attempt to close or seek an already closed stream

Technically I don't see what there's any issues with that, but there are two caveats:
1) As far as I can tell it's not possible to test the actual test case encountered here since it's not being properly picked up by pytest (since it's an exception on a __del__'ed object). We can test the error on calling close twice?
2) After discussions with @richardjgowers, I guess technically it's a band-aid on a deeper issue on `__del__` being called somewhere else? I'm not super convinced that it's not worth fixing this behaviour for now even as a band-aid though (especially since I'm not sure what the deeper issue is exactly).

I have raised #3507 as a proposed fix.
