### ISSUE TITLE
Error reading DlPoly HISTORY file

### ISSUE THREAD

**Issue by pcpatfire** [MDAnalysis/mdanalysis#3417]
## Expected behavior ##

I am trying reading a regular DlPoly HISTORY file.

## Actual behavior ##

I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sdu/work/work_env_3.9-qt_5.15.2/lib/python3.9/site-packages/MDAnalysis/core/universe.py", line 336, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/home/sdu/work/work_env_3.9-qt_5.15.2/lib/python3.9/site-packages/MDAnalysis/core/universe.py", line 122, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "/home/sdu/work/work_env_3.9-qt_5.15.2/lib/python3.9/site-packages/MDAnalysis/topology/DLPolyParser.py", line 140, in parse
    raise EOFError("End of file reached when reading HISTORY.")
EOFError: End of file reached when reading HISTORY.
```

## Code to reproduce the behavior ##
``` python

>>> import MDAnalysis as mda
>>> u = mda.Universe('DATA/HISTORY_1', format='history')
```
[HISTORY_1.zip](https://github.com/MDAnalysis/mdanalysis/files/7135026/HISTORY_1.zip)
DLPoly file version: 2.0 (Classic)

## Current version of MDAnalysis ##
MDAnalysis version: 2.0.0
Python version: 3.9.1
OS: CentOS 8

**Comment by orbeckst** [comment]
Do you know if anything changed in the DL_POLY HISTORY file format?

Are you able to read other history files?
