### ISSUE TITLE
COmpiling with pyInstaller

### ISSUE THREAD

**Issue by bhavaygg** [MDAnalysis/mdanalysis#3434]
I am trying to create a standalone GUI application that used MDAnalysis and was facing issues in the compilation.
```
Traceback (most recent call last):
  File "pyLFDA_gui.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "MDAnalysis\__init__.py", line 191, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "MDAnalysis\lib\__init__.py", line 39, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "MDAnalysis\lib\formats\__init__.py", line 23, in <module>
  File "MDAnalysis/lib/formats/libmdaxdr.pyx", line 1, in init MDAnalysis.lib.formats.libmdaxdr
ModuleNotFoundError: No module named 'MDAnalysis.lib.formats.cython_util'
```

Any idea how to fix this?

## Current version of MDAnalysis ##

- Which version are you using? `2.0.0`
- Which version of Python? `3.9.6` and `3.6.0`. Tested on both
- Which operating system? Windows 10 and WSL. Tested on both.

**Comment by IAlibay** [comment]
It looks like the cython code is not being compiled and/or imported? I unfortunately have no experience with pyinstaller, maybe one of the other devs knows better, but otherwise it might be something that needs to be asked upstream (i.e. to the pyinstaller folks)?
