### ISSUE TITLE
Benchmarks expect flags

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#3519]
## Expected behavior ##

The benchmarks run without error.

## Actual behavior ##

Some benchmarks fail because they expect flags that were removed in version 2.0.0. Here is a sampling of the errors:

```
For parameters: 'prop abs z <= 5.0', False, [True, False]
Traceback (most recent call last):
 File "/home/benchy/mambaforge/lib/python3.9/site-packages/asv/benchmark.py", line 1184, in main_run_server
   main_run(run_args)
 File "/home/benchy/mambaforge/lib/python3.9/site-packages/asv/benchmark.py", line 1058, in main_run
   result = benchmark.do_run()
 File "/home/benchy/mambaforge/lib/python3.9/site-packages/asv/benchmark.py", line 537, in do_run
   return self.run(*self._current_params)
 File "/home/benchy/mambaforge/lib/python3.9/site-packages/asv/benchmark.py", line 627, in run
   samples, number = self.benchmark_timing(timer, min_repeat, max_repeat,
 File "/home/benchy/mambaforge/lib/python3.9/site-packages/asv/benchmark.py", line 694, in benchmark_timing
   timing = timer.timeit(number)
 File "/home/benchy/mambaforge/lib/python3.9/timeit.py", line 177, in timeit
   timing = self.inner(it, self.timer)
 File "<timeit-src>", line 6, in inner
 File "/home/benchy/mambaforge/lib/python3.9/site-packages/asv/benchmark.py", line 599, in <lambda>
   func = lambda: self.func(*param)
 File "/home/benchy/mdanalysis/benchmarks/benchmarks/selections.py", line 76, in time_geometric_selections
   MDAnalysis.core.flags['use_periodic_selections'] = periodic_selection[0]
AttributeError: module 'MDAnalysis.core' has no attribute 'flags'
```

**Comment by orbeckst** [comment]
These flags can be removed since we are only benchmarking since 1.0.1 where these flags didn't exist anymore. One has to check if the equivalent behavior is now provided by kwargs for the methods.
