### ISSUE TITLE
Memory Error In Clustering

### ISSUE THREAD

**Issue by cplateVT** [MDAnalysis/mdanalysis#4127]
I performed a 250 ns MD simulation of a protein in water. I have 'protein.gro' and 'protein.xtc' which is a 6GB file containing only the trajectory for the protein. Note that in the Error, it says that 233 GiB are attempted to be loaded into memory. I am not sure why the operation would require 233 GiB

Error:
#############################################################################################
Traceback (most recent call last):
  File "/projects/deshmukhgroup/charlie/MD/P6-RdRp/run3/cluster.py", line 6, in <module>
    cluster_collection = encore.cluster(u, ncores=128)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cplate/miniconda3/envs/MDA/lib/python3.11/site-packages/MDAnalysis/analysis/encore/clustering/cluster.py", line 197, in cluster
    distance_matrix.append(get_distance_matrix(merged_ensemble,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cplate/miniconda3/envs/MDA/lib/python3.11/site-packages/MDAnalysis/analysis/encore/confdistmatrix.py", line 365, in get_distance_matrix
    confdistmatrix = conformational_distance_matrix(ensemble,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cplate/miniconda3/envs/MDA/lib/python3.11/site-packages/MDAnalysis/analysis/encore/confdistmatrix.py", line 169, in conformational_distance_matrix
    distmat = np.empty(matsize, np.float64)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 233. GiB for an array with shape (31250375001,) and data type float64
##############################################################################################
## Code to reproduce the behavior 

from MDAnalysis import Universe
import MDAnalysis.analysis.encore as encore
import pickle 

u = Universe('protein.gro','protein.xtc') 
cluster_collection = encore.cluster(u, ncores=128)

fi = open('output.pkl', 'w')

pickle.dump(cluster_collection, fi)
####################################################################
## Current version of MDAnalysis ##

- Which version are you using?  : 2.4.3

- Which version of Python : Python 3.11.3

- Which operating system? Linux

**Comment by orbeckst** [comment]
Have you tried running with fewer cores? It might be trying to load 128 copies of your trajectory into memory. How much memory do you have available? Start with lower core numbers, large numbers are almost certainly not giving you a linear speed up. I'd start with ncores=2 and 4.

**Comment by cplateVT** [comment]
I tried running the code with ncores=2, and the error was exactly the same:

#################################################################################
Traceback (most recent call last):
  File "/projects/deshmukhgroup/charlie/MD/P6-RdRp/run3/cluster.py", line 6, in <module>
    cluster_collection = encore.cluster(u, ncores=2)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cplate/miniconda3/envs/MDA/lib/python3.11/site-packages/MDAnalysis/analysis/encore/clustering/cluster.py", line 197, in cluster
    distance_matrix.append(get_distance_matrix(merged_ensemble,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cplate/miniconda3/envs/MDA/lib/python3.11/site-packages/MDAnalysis/analysis/encore/confdistmatrix.py", line 365, in get_distance_matrix
    confdistmatrix = conformational_distance_matrix(ensemble,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cplate/miniconda3/envs/MDA/lib/python3.11/site-packages/MDAnalysis/analysis/encore/confdistmatrix.py", line 169, in conformational_distance_matrix
    distmat = np.empty(matsize, np.float64)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 233. GiB for an array with shape (31250375001,) and data type float64
####################################################################################

**Comment by orbeckst** [comment]
@mtiberti @wouterboomsma any idea what might be happening in ENCORE to generate MemoryErrors?

**Comment by hmacdope** [comment]
Are you using a super large trajectory? ENCORE uses `.timeseries` and so will dump the whole traj to memory.

**Comment by cplateVT** [comment]
The trajectory file is 6GB, 125,000,000 frames. Not strided. My memory is 256 GB. It is likely that when all of the coordinates are loaded at once as float64, it is just too large. Just back of the napkin calculation here… but 125M frames x 100 alpha carbons x 3 (xyz) gives approximately 30B floats, which accounts for the amount of data raised in the exception. I suppose my only option would be to stride the trajectory then?
