### ISSUE TITLE
Stream types for topology and trajectory snag at Universe init

### ISSUE THREAD

**Issue by xperrylinn** [MDAnalysis/mdanalysis#4173]
## Expected behavior ##

I have a workflow where I'd like to be able to feed in my PDB topology and DCD trajectory data from streams. The [Universe](https://docs.mdanalysis.org/2.5.0/documentation_pages/core/universe.html#MDAnalysis.core.universe.Universe) docs suggest I'm able to provide stream types for the topology and trajectory init arguments, but when I try to do so using example codes below, I surfaced a couple of snags. For context, I'm able to load the associated topology and trajectory files without issue into a visualization tool such as MolecularNodes and Blendr.

Am I using the stream argument type option correctly? Any help is greatly appreciated. Thank you!

## Actual behavior ##

Output from example code one:

```
Traceback (most recent call last):
  File "/Users/xperrylinn/Documents/Academics/MSSE/spring_2023/Capstone/atomate2-openmm/scripts/debug_mdanalysis_streams.py", line 13, in <module>
    universe = mda.Universe(
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 346, in __init__
    topology = _topology_from_file_like(self.filename,
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 110, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/topology/PDBParser.py", line 207, in parse
    top = self._parseatoms()
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/topology/PDBParser.py", line 385, in _parseatoms
    residx, (resids, resnames, icodes, resnums, segids) = change_squash(
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/topology/base.py", line 207, in change_squash
    new[i] = old[x:y][0]  # TODO: Check that x:y is the same
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Output from example code two, where I replaced the topology stream with a file path to see if the DCD steam was working as it appears to get processed after the topology:

OSError: Reading DCD header failed: format of DCD file is wrong
Exception ignored in: 'MDAnalysis.lib.formats.libdcd.DCDFile._read_header'
Traceback (most recent call last):
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/coordinates/DCD.py", line 144, in __init__
    self._file = DCDFile(self.filename)
OSError: Reading DCD header failed: format of DCD file is wrong
IndexError: index 0 is out of bounds for axis 1 with size 0
Exception ignored in: 'MDAnalysis.lib.formats.libdcd.DCDFile._setup_buffers'
Traceback (most recent call last):
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/coordinates/DCD.py", line 144, in __init__
    self._file = DCDFile(self.filename)
IndexError: index 0 is out of bounds for axis 1 with size 0
Traceback (most recent call last):
  File "/Users/xperrylinn/Documents/Academics/MSSE/spring_2023/Capstone/atomate2-openmm/scripts/debug_mdanalysis_streams.py", line 13, in <module>
    universe = mda.Universe(
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 365, in __init__
    self.load_new(coordinates, format=format, in_memory=in_memory,
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/core/universe.py", line 567, in load_new
    self.trajectory = reader(filename, format=format, **kwargs)
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/lib/util.py", line 2522, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/xperrylinn/miniconda3/envs/atomate2-openmm/lib/python3.8/site-packages/MDAnalysis/coordinates/DCD.py", line 155, in __init__
    frame = self._file.read()
  File "MDAnalysis/lib/formats/libdcd.pyx", line 562, in MDAnalysis.lib.formats.libdcd.DCDFile.read
OSError: opened empty file. No frames are saved

## Code to reproduce the behavior ##

Example code one:
``` python
import MDAnalysis as mda
import io

topology_file_path = "topology.pdb"
trajectory_file_path = "trajectory.dcd"

with open(trajectory_file_path, 'rb') as file:
    trajectory_blob = file.read()

str_stream = io.StringIO(topology_file_path)
bytes_stream = io.BytesIO(trajectory_blob)

universe = mda.Universe(
    topology=str_stream,
    topology_format="PDB",
    coordinates=bytes_stream,
    format="DCD",
)
```

Example code two:
``` python
import MDAnalysis as mda
import io

topology_file_path = "topology.pdb"
trajectory_file_path = "trajectory.dcd"

with open(trajectory_file_path, 'rb') as file:
    trajectory_blob = file.read()

bytes_stream = io.BytesIO(trajectory_blob)

universe = mda.Universe(
    topology=topology_file_path,
    topology_format="PDB",
    coordinates=bytes_stream,
    format="DCD",
)
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`): 2.4.3
- Which version of Python (`python -V`)?: Python 3.8.16
- Which operating system? MacOS Intel Chip

**Comment by orbeckst** [comment]
In short: Getting real streaming support to work is an upcoming project. Current support is patchy and not well tested; a key problem is that our coordinate readers all assume that they can seek a stream. 

Although seeking should be possible on io.BytesIO, I don't think we ever tried it out. You could check if you can do the same with a simple XYZ trajectory instead of a binary format.

At a minimum, our docs should not imply that streaming of trajectories "just works".

**Comment by linjiahao962889027** [comment]
The MDAnalysis's reader class is written in Cython. In the C code, the open file function only receives a filename which is of type string (char *). Therefore, the Universe initialization can only accept a filename as a string, not a stream. Perhaps we can use a custom reader to solve this problem. Additionally, the parameter 'Format' is a class, using the class name.
