### ISSUE TITLE
[BUG] ```ClusterCollection``` object has no attribute ```metadata```

### ISSUE THREAD

**Issue by HeetVekariya** [MDAnalysis/mdanalysis#4413]
## Additional Information

- This issue is originally found in [Issue 3925](https://github.com/MDAnalysis/mdanalysis/issues/3925#issuecomment-1868292405). Please have a look in that conversation.

## Expected behavior ##
- **```ClusterCollection```** object/instance has **```metadata```** parameter associated with it. We can check [here](https://docs.mdanalysis.org/2.7.0/documentation_pages/analysis/encore/clustering.html#MDAnalysis.analysis.encore.clustering.ClusterCollection.ClusterCollection).
- Hence **```metadata```** of **```ClusterCollection```** object/instance should be accessible.

## Actual behavior ##

- When we try to access **```metadata```** of **```ClusterCollection```** object/instance then it gives below error
```bash

[<class 'MDAnalysis.analysis.encore.clustering.ClusterCollection.ClusterCollection'>, 
<class 'MDAnalysis.analysis.encore.clustering.ClusterCollection.ClusterCollection'>]

Traceback (most recent call last):
  File "/home/heet/Work/Development/mdanalysis/test.py", line 27, in <module>
    print([cluster.metadata for cluster in cluster_collection][:2])
  File "/home/heet/Work/Development/mdanalysis/test.py", line 27, in <listcomp>
    print([cluster.metadata for cluster in cluster_collection][:2])

AttributeError: 'ClusterCollection' object has no attribute 'metadata'
```

## Code to reproduce the behavior ##
- Below code is from **```cluster.py```** ( [here](https://github.com/MDAnalysis/mdanalysis/blob/734314b8b7b70617a92eb505f75844e6837505ca/package/MDAnalysis/analysis/encore/clustering/cluster.py#L147) ).

```python
from MDAnalysis import Universe
import MDAnalysis.analysis.encore as encore
from MDAnalysis.tests.datafiles import PSF, DCD, DCD2
ens1 = Universe(PSF, DCD)
ens2 = Universe(PSF, DCD2)
cluster_collection = encore.cluster([ens1,ens2])

cluster_collection = encore.cluster([ens1,ens2], method=encore.DBSCAN())

cluster_collection = encore.cluster([ens1,ens2], method=[encore.AffinityPropagationNative(preference=-1.), encore.AffinityPropagationNative(preference=-2.)])

print([cluster.metadata for cluster in cluster_collection][:2])
```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
  - **```2.6.1```**
- Which version of Python (`python -V`)?
  - **```Python 3.10.13```**
- Which operating system?
  - **```Ubuntu```**

**Comment by IAlibay** [comment]
Migrating to mdaencore, this is no longer in the realm of the core library.
