### ISSUE TITLE
 Python 3.12 deprecated SafeConfigParser

### ISSUE THREAD

**Issue by nataliyah123** [MDAnalysis/mdanalysis#4441]
## Error ##

When I do `python -m pip install msmb_theme==1.2.0`.  I get the following error. `AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`  mdanalysis_sphinx_theme needs msmb-theme to be installed.
I am unable to run make doctest 
msmb-theme has not been updated for quite some time. and from 3.12 SafeConfigParser has been [deprecated](https://docs.python.org/3.12/whatsnew/3.12.html#configparser). 
```

Collecting msmb_theme
  Using cached msmb_theme-1.2.0.tar.gz (54 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-6g0ik8_f/msmb-theme_ce47477fd93e4fdfa525b8b1542102c4/versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6g0ik8_f/msmb-theme_ce47477fd93e4fdfa525b8b1542102c4/setup.py", line 15, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-6g0ik8_f/msmb-theme_ce47477fd93e4fdfa525b8b1542102c4/versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-6g0ik8_f/msmb-theme_ce47477fd93e4fdfa525b8b1542102c4/versioneer.py", line 1339, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-6g0ik8_f/msmb-theme_ce47477fd93e4fdfa525b8b1542102c4/versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(mdanalysis-dev) ibia@Sumaira:/mnt/c/WINDOWS/system32$ python -m pip install --upgrade msmb_theme
Collecting msmb_theme
  Using cached msmb_theme-1.2.0.tar.gz (54 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-qeb30rrt/msmb-theme_c4b84e1edd104d35b0ab70ff01694d98/versioneer.py:467: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qeb30rrt/msmb-theme_c4b84e1edd104d35b0ab70ff01694d98/setup.py", line 15, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-qeb30rrt/msmb-theme_c4b84e1edd104d35b0ab70ff01694d98/versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-qeb30rrt/msmb-theme_c4b84e1edd104d35b0ab70ff01694d98/versioneer.py", line 1339, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-qeb30rrt/msmb-theme_c4b84e1edd104d35b0ab70ff01694d98/versioneer.py", line 399, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details. 
```
Other than this, there were some other dependencies that were downgraded during installation process. 

## Current version of MDAnalysis ##

- My python version is 3.12.1
- My MDAnalysis version is 2.8.0-dev
- WSL (ubuntu)

**Comment by IAlibay** [comment]
@nataliyah123 - msmb_theme isn't used by MDAnalysis anymore as far as I remember. Could you tell me which instructions you are looking at which are telling you to install this?

**Comment by IAlibay** [comment]
I see, the UserGuide's current stable release is still pointing to the old instructions: https://userguide.mdanalysis.org/stable/contributing_code.html#id1

@nataliyah123 apologies - this is because a new release of the userguide has not been released yet. If you are looking to contribute to MDAnalysis, you should instead be looking at the development version of the userguide, please see here instead: https://userguide.mdanalysis.org/dev/contributing_code.html#id1

There is already an issue open in the userguide about doing a new deployment https://github.com/MDAnalysis/UserGuide/issues/350, so I'm going to go ahead and close this issue.

**Comment by nataliyah123** [comment]
@IAlibay.  thanks for the reply. I wasn't following the stable (2.7.0) instructions. I was following [2.8.0-dev](https://docs.mdanalysis.org/dev/index.html) and that too is pointing to 2.6.1.

**Comment by IAlibay** [comment]
@nataliyah123 I see what you mean - unfortunately there's no way (as far as I can tell) to dynamically change links based on if you are looking at the development or stable documentation, so our API development docs will always point to the stable UserGuide. To see the userguide developments docs you have to remember to manually change the version with the bottom left selector.
