### ISSUE TITLE
PDB read, failed to construct topology for big index number (>99999) 

### ISSUE THREAD

**Issue by alejob** [MDAnalysis/mdanalysis#446]
When I load the universe in this way:

```python
universe = MDAnalysis.Universe("step5_assembly.pdb", "../WT_run1_1000_1ps.dcd") 
```
I have the next error:

*File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/AtomGroup.py", line 3705, in __init__
    "Error: {2}".format(self.filename, parser, err))
ValueError: Failed to construct topology from file step5_assembly.pdb with parser <class 'MDAnalysis.topology.PrimitivePDBParser.PrimitivePDBParser'> 
Error: invalid literal for int() with base 10: '*****'*

 I have more than 100000 atoms, so after the 99999 index, its appear the *****, here is the part of the pdb:

```
...
ATOM  99998  H2  TIP3 2390      64.326  44.891  14.267  1.00  0.00      TIP3
ATOM  99999  OH2 TIP3 2391      67.275  48.893  23.568  1.00  0.00      TIP3
ATOM  *****  H1  TIP3 2391      66.641  48.181  23.485  1.00  0.00      TIP3
ATOM  *****  H2  TIP3 2391      66.986  49.547  22.931  1.00  0.00      TIP3
ATOM  *****  OH2 TIP3 2392      60.459  51.771  21.399  1.00  0.00      TIP3
...
```

Maybe a solution could be to create an extension similar to XPDB (that read 5-digit residue numbers ), or like Oliver suggest,  ignore the atom number.

**Comment by richardjgowers** [comment]
So I think the offending line is:
```
                    serial = int(line[6:11])
```

`serial` is later used to map the indices of bonds to "our" numbering system.  

Does using `permissive=True` in the Universe init make the file parse properly?

**Comment by richardjgowers** [comment]
Also, if this file is the "normal" output of a program, it's worth adding as a test case.  I think adding 100,000 lines of ascii is a bad idea, but maybe we could either
 - add a minimal example that has `***` as numbers (eg 4 atoms called 1, 2, `****`, `****`)
 - add some sort of generator that creates this file to test it

**Comment by alejob** [comment]
I try your suggestion, ```permissive=True```, but I still have the same problem.

**Comment by richardjgowers** [comment]
So just to check, can you try this?

``` python
from MDAnalysis.topology.PDBParser import PDBParser

struc = PDBParser(filename).parse()

from MDAnalysis.topology.PrimitivePDBParser import PrimitivePDBParser

struc2 = PrimitivePDBParser(filename).parse()
```

And see if either give you something usable?

**Comment by alejob** [comment]
The first works with a warning, the second still gives an error. I copy exactly what a try:

```python
from MDAnalysis.topology.PDBParser import PDBParser                                                     
                                                                                                        
struc = PDBParser("step5_assembly.pdb").parse()                                                         
                                                                                                        
from MDAnalysis.topology.PrimitivePDBParser import PrimitivePDBParser                                   
                                                                                                        
struc2 = PrimitivePDBParser("step5_assembly.pdb").parse() 

```

and this was the output

```
/usr/local/lib/python2.7/dist-packages/Bio/PDB/PDBParser.py:287: PDBConstructionWarning: PDBConstructionException: Invalid or missing B factor at line 23786.
Exception ignored.
Some atoms or residues may be missing in the data structure.
  % message, PDBConstructionWarning)
<!--HERE FINISH THE FIRST PARSER-->
Traceback (most recent call last):
  File "testMSD_doc.py", line 11, in <module>
    struc2 = PrimitivePDBParser("step5_assembly.pdb").parse()
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PrimitivePDBParser.py", line 78, in parse
    atoms = self._parseatoms()
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PrimitivePDBParser.py", line 100, in _parseatoms
    serial = int(line[6:11])
ValueError: invalid literal for int() with base 10: '*****'
```

**Comment by richardjgowers** [comment]
Hm, so does loading like this work?
``` python
u = mda.Universe('file.pdb','file.dcd', topology_format='PDB')
```

**Comment by alejob** [comment]
No, when I run it I obtain
```
Traceback (most recent call last):
  File "testMSD_doc.py", line 18, in <module>
    universe = MDAnalysis.Universe("step5_assembly.pdb", "../WT_run1_1000_1ps.dcd", topology_format="PDB") 
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/AtomGroup.py", line 3705, in __init__
    "Error: {2}".format(self.filename, parser, err))
ValueError: Failed to construct topology from file step5_assembly.pdb with parser <class 'MDAnalysis.topology.PrimitivePDBParser.PrimitivePDBParser'>
```
that is, I'm still using the PrimitivePDBParser using the topology_format 'PDB' like option. After this I read the documentation  (http://pythonhosted.org/MDAnalysis/documentation_pages/topology/init.html ) and try:
```python
universe = MDAnalysis.Universe("step5_assembly.pdb", "../WT_run1_1000_1ps.dcd", permissive=False) 
```
and it works :+1: , but with the same warning

```
/usr/local/lib/python2.7/dist-packages/Bio/PDB/PDBParser.py:287: PDBConstructionWarning: PDBConstructionException: Invalid or missing B factor at line 23786.
Exception ignored.
Some atoms or residues may be missing in the data structure.
  % message, PDBConstructionWarning)
```
