### ISSUE TITLE
improve error message when writing PQR without radii present

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#481]
I cannot create a PQR file from a simple PDB. Some of the fields have different meanings but they should be replaced with default values.

```
MODEL
CRYST1 80.000   80.000   80.000  60.00  60.00  90.00
ATOM      1 N    MET     1      00.000  00.000  00.000  1.00 84.71
ATOM      2 N    ARG     2      01.000  01.000  01.000  1.00 68.59
ATOM      3 N    ILE     3      02.000  02.000  02.000  1.00 48.30
ATOM      4 N    LYS     4      03.000  03.000  03.000  1.00 49.38
ATOM      5 N    LEU     5      04.000  04.000  04.000  1.00 42.10
END
```

``` python
def create_test_trj(uni, fname, wrong_natoms=False):
    n_atoms = uni.atoms.n_atoms
    if wrong_natoms:
        n_atoms -= 2
    pos = np.arange(3 * n_atoms).reshape(n_atoms, 3)
    uni.trajectory.ts.dt = 1
    with mda.Writer(fname, n_atoms) as w:
        for i in range(5):
            uni.atoms.positions = 2 ** i * pos
            uni.trajectory.ts.time = i
            w.write(uni)


def main():
    pdb = 'test_topology.pdb'
    u = mda.Universe(pdb)

    create_test_trj(u, 'test.pqr')
```

```
python create_data.py            1 ↵
Traceback (most recent call last):
  File "create_data.py", line 26, in <module>
    main()
  File "create_data.py", line 23, in main
    create_test_trj(u, 'test.pqr')
  File "create_data.py", line 16, in create_test_trj
    w.write(uni)
  File "/home/max/.local/lib/python2.7/site-packages/MDAnalysis/coordinates/PQR.py", line 247, in write
    atom.charge, atom.radius)
  File "/home/max/.local/lib/python2.7/site-packages/MDAnalysis/coordinates/PQR.py", line 272, in _write_ATOM
    fh.write(ATOM.format(serial, atomName, residueName, chainID, residueNumber, XYZ, charge, radius))
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by orbeckst** [comment]
I don't think that this has to work; for instance, for a PQR file you need charges and radii and it makes no sense to set defaults for them.

Failing explicitly with a good error message would be more important here, e.g. "don't have charges and radii in the topology but I REALLY need those for a PQR".

**Comment by orbeckst** [comment]
Btw, did you try setting radii and charges before writing?
```python
u.atoms.set_radii(0.0)
```
worked for me.

I think that we really only need a better error message for the `PQRWriter`.

**Comment by kain88-de** [comment]
I did not do that. But yeah I agree then that we just need a better error message

**Comment by richardjgowers** [comment]
Ok this is mostly fixed by 363. Writing a PQR now works, but gives a warning about missing radii
```
/home/richard/miniconda2/envs/mdadev/lib/python2.7/site-packages/MDAnalysis/coordinates/PQR.py:268: UserWarning: Supplied AtomGroup was missing the following attributes: charges, radii. These will be written with default values. 
  "".format(miss=', '.join(missing_topology)))
```

Radii can be added like this:
```python
In [8]: from MDAnalysis.core.topologyattrs import Radii

In [9]: import numpy as np

In [10]: rad = np.arange(len(u.atoms)) + 1.0  # or possibly useful values...

In [11]: u.add_TopologyAttr(Radii(rad))



```
