### ISSUE TITLE
4 unpickle tests are failing in 0.12.1 on Fedora rawhide

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/mdanalysis#487]
Hello,
the following four tests are failing when doing a build and running the testsuite on Fedora rawhide:
```
$ cd MDAnalysisTests-0.12.1/MDAnalysisTests
$ PYTHONPATH=/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages:/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib64/python2.7/site-packages /usr/bin/python2 ./mda_nosetests -v
[...]
Test that an AtomGroup can be unpickled (Issue 293) ... FAIL
test_unpickle_noanchor (MDAnalysisTests.test_persistence.TestAtomGroupPickle) ... FAIL
test_unpickle_reanchor (MDAnalysisTests.test_persistence.TestAtomGroupPickle) ... ok
test_unpickle_reanchor_other (MDAnalysisTests.test_persistence.TestAtomGroupPickle) ... ok
test_unpickle_rename (MDAnalysisTests.test_persistence.TestAtomGroupPickle) ... FAIL
test_unpickle_wrongname (MDAnalysisTests.test_persistence.TestAtomGroupPickle) ... FAIL
[...]

======================================================================
FAIL: Test that an AtomGroup can be unpickled (Issue 293)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/test_persistence.py", line 61, in test_unpickle_named
    assert_(newag.universe is self.universe_n, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_noanchor (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/test_persistence.py", line 79, in test_unpickle_noanchor
    assert_raises(RuntimeError, cPickle.loads, self.pickle_str)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1099, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: RuntimeError not raised
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_rename (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/test_persistence.py", line 116, in test_unpickle_rename
    assert_(newag.universe is self.universe, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_wrongname (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/test_persistence.py", line 107, in test_unpickle_wrongname
    assert_raises(RuntimeError, cPickle.loads, self.pickle_str_n)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1099, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: RuntimeError not raised
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/builddir/build/BUILDROOT/python-MDAnalysis-0.12.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
Ran 2569 tests in 449.142s

FAILED (KNOWNFAIL=4, SKIP=2, failures=4)
```
Additionally, a lot more tests fail if I try to run them in parallel.

**Comment by mnmelo** [comment]
Thanks for reporting this. We've come across the same, as reported in #478. But I can't reproduce that locally (on Ubuntu 14.04).

I'll try to set up a virtualenv to test this and report back. Maybe I'll need your help, in case I can't reproduce the errors.

**Comment by richardjgowers** [comment]
Re the tests failing in parallel, how are you running them in parallel? You have to also set the `process-timeout` option too.

```
path_to_MDAnalysisTests/mda_nosetests -v --parallel-processes=4 --process-timeout=120
```

**Comment by rathann** [comment]
It's actually `--processes`, not `--parallel-processes`, but yes, adding `--process-timeout` does help.

I'll be happy to provide any information you need to reproduce this.

**Comment by orbeckst** [comment]
I added a vagrant VM for Fedora 21 (in 44b9a1611e5e4b89ceba8df9543b49870f636abe) and the persistence unit tests fail there, so @mnmelo could use it for looking into this in a bit more detail. 

Boot vm and ssh into it:
```
cd vm/Fedora/21
vagrant up
vagrant ssh
```
I didn't find a way to run a specific set of tests from within ipython (... eg. `MDAnalysisTests.run('MDAnalysisTests.test_persistence', verbose=3)` did not work at all because it ignores the module and tests everything and also does not understand verbose) so I did the following:
```
# get mda_nosetest mini script (not installed with MDAnalysisTests!)
wget https://raw.githubusercontent.com/MDAnalysis/mdanalysis/develop/testsuite/MDAnalysisTests/mda_nosetests  -O ~/mda_nosetest 
chmod a+x ~/mda_nosetest
cd /usr/lib/python2.7/site-packages/MDAnalysisTests
~/mda_nosetest -v test_persistence.py
```
With 0.12.1 I get two tests failing:
```
======================================================================
FAIL: test_unpickle_noanchor (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/MDAnalysisTests/test_persistence.py", line 79, in test_unpickle_noanchor
    assert_raises(RuntimeError, cPickle.loads, self.pickle_str)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 1020, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: RuntimeError not raised
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_reanchor_other (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/MDAnalysisTests/test_persistence.py", line 100, in test_unpickle_reanchor_other
    assert_(newag.universe is self.universe_n, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 44, in assert_
    raise AssertionError(msg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/lib/python2.7/site-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 33 tests in 62.867s

FAILED (failures=2)
```

**Comment by mnmelo** [comment]
So, I 'm using the vagrant vm you set up, @orbeckst (with the bento/fedora-21 box), but am hitting many more errors. The tests don't even complete because there's a segfault (!!) along the way. I probably have something set up wrong and will try to fix it, but might have to come back to you for help, @orbeckst, ok?

As to the proper test invocation, only now have I noticed that `mda_nosetests` isn't being shipped with the pip `MDAnalysisTests` package. Is there a reason not to? Not that it matters much; the same functionality --namely, specific file testing-- is accessible by invoking
```python
from MDAnalysis.tests import test
test(argv=["--exe", "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py"])
```
The arguments to `test` are just the same as are passed to `mda_nosetests`.
I updated the wiki to only mention `mda_nosetests` in the context of testing in your cloned repo, but I vote that we should start shipping it anyway.

Finally, in checking out that the distribution really doesn't have `mda_nosetests` I also found out that those and more persistence errors crop up in my Ubuntu 14.04 install (tested on the pip install), plus two more on `TestPSAnalysis` (apparently permission related; not running as root). Can you confirm, @orbeckst?

```
======================================================================
ERROR: test_hausdorff_bound (MDAnalysisTests.test_analysis.TestPSAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_analysis.py", line 568, in setUp
    path_select='name CA')
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/analysis/psa.py", line 1131, in __init__
    os.makedirs(targetdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: './psadata'
-------------------- >> begin captured logging << --------------------
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims.dcd...
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims2.dcd...
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims.dcd...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_reversal_frechet (MDAnalysisTests.test_analysis.TestPSAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_analysis.py", line 568, in setUp
    path_select='name CA')
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/analysis/psa.py", line 1131, in __init__
    os.makedirs(targetdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: './psadata'
-------------------- >> begin captured logging << --------------------
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims.dcd...
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims2.dcd...
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims.dcd...
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_reversal_hausdorff (MDAnalysisTests.test_analysis.TestPSAnalysis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_analysis.py", line 568, in setUp
    path_select='name CA')
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysis/analysis/psa.py", line 1131, in __init__
    os.makedirs(targetdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: './psadata'
-------------------- >> begin captured logging << --------------------
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims.dcd...
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims2.dcd...
MDAnalysis.topology.PSF: DEBUG: PSF file /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk.psf: format STANDARD
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_dims.dcd...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Test that an AtomGroup can be unpickled (Issue 293)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py", line 61, in test_unpickle_named
    assert_(newag.universe is self.universe_n, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_noanchor (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py", line 79, in test_unpickle_noanchor
    assert_raises(RuntimeError, cPickle.loads, self.pickle_str)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1099, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: RuntimeError not raised
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_reanchor (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py", line 91, in test_unpickle_reanchor
    assert_(newag.universe is self.universe, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_reanchor_other (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py", line 100, in test_unpickle_reanchor_other
    assert_(newag.universe is self.universe_n, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...                                                                                    21:34:02
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/21:34:02b/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_rename (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py", line 116, in test_unpickle_rename
    assert_(newag.universe is self.universe, "Unpickled AtomGroup on wrong Universe.")
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 53, in assert_
    raise AssertionError(smsg)
AssertionError: Unpickled AtomGroup on wrong Universe.
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_unpickle_wrongname (MDAnalysisTests.test_persistence.TestAtomGroupPickle)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/test_persistence.py", line 107, in test_unpickle_wrongname
    assert_raises(RuntimeError, cPickle.loads, self.pickle_str_n)
  File "/usr/local/lib/python2.7/dist-packages/numpy/testing/utils.py", line 1099, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: RuntimeError not raised
-------------------- >> begin captured logging << --------------------
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading ('/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb', '/usr/local/lib/python2.7/dist-packages/MDAnalysisTests/data/adk_open.pdb')...
--------------------- >> end captured logging << ---------------------
```
I'm at a loss, but it starts seeming to me it might be related to how the package is deployed.

**Comment by richardjgowers** [comment]
Just to clarify, `mda_nosetests` is shipped as part of the package, but not installed anywhere.  So kind of invisibly shipped.

https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MANIFEST.in

I think the cleanest/easiest way for people to test their installation is `MDAnalysis.tests.test()`, is there a reason why the script is better than this?

**Comment by mnmelo** [comment]
Not really better. I made the effort to have it so that devs with a `nosetests` workflow would get to keep it.

Making provisions for the dual-testing mode (`mda_nosetests` and `MDAnalysis.tests.test()`) actually forces the syntax of the latter to be a bit convoluted. If we'd settle on `MDAnalysis.tests.test()` things would get cleaner. Still, I think it's a plus to keep `nosetests` compatibility.

**Comment by orbeckst** [comment]
On 18 Oct, 2015, at 00:30, mnmelo wrote:

> So, I 'm using the vagrant vm you set up, @orbeckst (with the bento/fedora-21 box), but am hitting many more errors. The tests don't even complete because there's a segfault (!!) along the way. I probably have something set up wrong and will try to fix it, but might have to come back to you for help, @orbeckst, ok?

I have only tested the vm's properly on Mac OS X 10.6.8 (!) with 

- vagrant 1.6.3
- VirtualBox 4.3.12

With the standard VM I don't have enough memory to run all the tests so I haven't done that yet (also, I have to figure out how to do this on a bigger machine than my aging laptop so that I could provide the VM with more cores and more memory to properly run the tests). I only quickly checked the test_pickling with the posted results.

My superficial search of vagrant boxes did not find a rawhide box and so I don't know how good of a test bed Fedora 21 is --- I haven't used that distro in a while.

**Comment by orbeckst** [comment]
Regarding errors in the *psa* module: I don't see the one that you describe. (I used the Fedora vm):
```
In [8]: MDAnalysis.tests.test(argv=["--exe", "/usr/lib/python2.7/site-packages/MDAnalysisTests/test_analysis.py"])
...S.....S....................................................
----------------------------------------------------------------------
Ran 62 tests in 19.620s

OK (SKIP=2)
An exception has occurred, use %tb to see the full traceback.

SystemExit: False

To exit: use 'exit', 'quit', or Ctrl-D.
```
Admittedly, I don't understand *why* it passes for me because the PSA testing code contains [test_analysis.py#L586](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/)
```python
shutil.rmtree('psadata') # remove psa data directory
```
and I have no idea where this directory comes from or is written to; it almost certainly should be using the `tempdir` functionality #440 — @sseyler can you comment?

**Comment by orbeckst** [comment]
Finally, chiming in on `mda_nosetest` vs `MDAnalysis.tests.test()`: Both should work but it would be nice if the latter was either documented with examples (I only learnt from *this* issue how to use it) or had a more intuitive syntax.

(By the way, running `MDAnalysisTests.test_analysis.test()` runs unit tests for numpy and not for our module — *that* confused me for a while...)

**Comment by mnmelo** [comment]
OK, I updated the wiki to try and make testing examples clearer.

**Comment by richardjgowers** [comment]
So the VM is maybe the cleanest way to test things, but I think we can get away using a virtual environment.. it's what I used to test the release.  Maybe this isn't as feasible in OSX though. I followed this guide for virtual envs:

http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by mnmelo** [comment]
Ok, I think I found the problem: when an `AtomGroup` is unpickled we look in `MDAnalysis._anchor_universes` for a suitable `Universe` to unpickle it onto.

`MDAnalysis._anchor_universes` is a `WeakSet`, which means that dead `Universes` just disappear from it. However, this only happens at garbage-collection time. When running the unpickling tests, the `Universes` set up in the first tests linger on, and remain present when later tests are run. This is what broke the tests. My solution is to manually invoke `gc.collect()` when unpickling an `AtomGroup`.

This was also something of a heisenbug, since subtle execution differences might mask it:
 - Running in high parallelization seems to avoid it somewhat, probably because the different tests are run by different processes, and therefore there are no lingering `Universes` per process;
 - Checking for memleaks also masks it, because there's an implicit garbage collection done by the memleak tester (that's why travis was happy);
 - Low-memory systems may also fare better, since low memory might trigger garbage collection more often.

That said, there is probably much on how nose decides to run the tests that I don't grasp, and that will also play a role (running the whole test suite brought up more unpickling errors than running just the `test_persistence.py` testfile) . That should explain the different number of errors under different settings.

I don't know whether this warrants the discussion of different test setups (with and without parallelization/memleak testing, etc.)
