### ISSUE TITLE
`NamedStream` is not compatible with Python 3

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#649]
The definition of the `NamedStream` class is one of the things that prevent MDAnalysis for being imported in python 3 (see #634):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jon/dev/mda3/package/MDAnalysis/__init__.py", line 151, in <module>
    from .lib import log
  File "/home/jon/dev/mda3/package/MDAnalysis/lib/__init__.py", line 28, in <module>
    from . import util
  File "/home/jon/dev/mda3/package/MDAnalysis/lib/util.py", line 459, in <module>
    class NamedStream(io.IOBase, basestring):
NameError: name 'basestring' is not defined
```

This error is due to `basestring` no longer existing in python 3 while the `NameString` class inherit from it. The most obvious fix would be to replace the inheritance to `basetring` to an inheritance to `str` in python 3 and `unicode` in python 2 (or to `six.text_type` to hide the version specific typing). Doing so also fails because `NamedStream` also inherit from `io.IOStream` and it creates a conflict:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jon/dev/mda3/package/MDAnalysis/__init__.py", line 151, in <module>
    from .lib import log
  File "/home/jon/dev/mda3/package/MDAnalysis/lib/__init__.py", line 28, in <module>
    from . import util
  File "/home/jon/dev/mda3/package/MDAnalysis/lib/util.py", line 459, in <module>
    class NamedStream(io.IOBase, str):
  File "/home/jon/Envs/mda3/lib/python3.4/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
TypeError: multiple bases have instance lay-out conflict
```

**Comment by orbeckst** [comment]
Maybe we can solve the problem with a different approach that allows you to inspect the "filename" of the stream as if it were a string – but I don't know what this would be. The solution that I implemented seemed the most straightforward at the time.

If worst comes to worst, define one class for Py 3 and the other for Py 2. That would probably be a sign that a smarter solution exists but if it is workable...

Final possibility: Remove it and make it an extra mini package and we worry about Py 3 for that one when someone (=probably I...) gets desperate to use it. I really like the functionality for interfacing with legacy code and I use it but it's not really used inside MDA (IIRC) and this is not worth holding up Py3.

**Comment by orbeckst** [comment]
I'm curious why you closed the issue --- is it resolved in any way?

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Jan 22, 2016 um 7:52 schrieb Richard Gowers <notifications@github.com>:

**Comment by richardjgowers** [comment]
Ah sorry, the PR didn't get linked #652
