### ISSUE TITLE
Memleak nose plugin does not work on python 3

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/mdanalysis#662]
When running the tests on python 3 with the memleak plugin activated (see #658), all tests error with a traceback similar to:

```
Traceback (most recent call last):
  File "/home/jon/Envs/mda3/lib/python3.4/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/home/jon/Envs/mda3/lib/python3.4/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/lib/python3.4/unittest/case.py", line 625, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.4/unittest/case.py", line 553, in run
    result.startTest(self)
  File "/home/jon/Envs/mda3/lib/python3.4/site-packages/nose/proxy.py", line 169, in startTest
    self.plugins.startTest(self.test)
  File "/home/jon/Envs/mda3/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/jon/Envs/mda3/lib/python3.4/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/jon/dev/mdanalysis/testsuite/MDAnalysisTests/plugins/memleak.py", line 68, in startTest
    rp = test.test._resultForDoCleanups
AttributeError: 'MethodTestCase' object has no attribute '_resultForDoCleanups'
```

**Comment by kain88-de** [comment]
Is there an option run those test inside of ipython and into the debugger when the attributeError occurs?

**Comment by jbarnoud** [comment]
I found 
<http://stackoverflow.com/questions/4950637/setting-breakpoints-with-nosetests-pdb-option> 
but I do not know how it applies in that case.

**Comment by mnmelo** [comment]
Ok, fixed the problem. I actually found a much better way to register the memleak test hook, and the plugin is now much more elegant.

On the other hand, as explained in [PEP 442](https://www.python.org/dev/peps/pep-0442/), from python 3.4 onward leaks from circular references are now cleanly handled. It seems we won't be needing my (now beautiful) plugin with python 3 :cry:
