### ISSUE TITLE
two test failures on Fedora 22

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/mdanalysis#770]
### Expected behaviour

Tests pass.
### Actual behaviour

```
[...]
======================================================================
FAIL: test_delta (MDAnalysisTests.analysis.test_density.TestDensity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.14.0-2.fc22.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/analysis/test_density.py", line 69, in test_delta
    assert_almost_equal(self.D.delta, deltas)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 474, in assert_almost_equal
    return assert_array_almost_equal(actual, desired, decimal, err_msg)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 842, in assert_array_almost_equal
    precision=decimal)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 620, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals

(shapes (3, 3), (3,) mismatch)
 x: array([[ 3.3333333,  0.       ,  0.       ],
       [ 0.       ,  2.5      ,  0.       ],
       [ 0.       ,  0.       ,  2.       ]])
 y: array([ 3.3333333,  2.5      ,  2.       ])

======================================================================
FAIL: test_grid (MDAnalysisTests.analysis.test_density.TestDensity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.14.0-2.fc22.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/analysis/test_density.py", line 74, in test_grid
    assert_almost_equal(self.D.grid.sum() * dV, self.counts)
  File "/usr/lib64/python2.7/site-packages/numpy/testing/utils.py", line 490, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.0
 DESIRED: 100
[...]
----------------------------------------------------------------------
Ran 3342 tests in 103.529s

FAILED (KNOWNFAIL=3, SKIP=5, failures=2)
```
### Code to reproduce the behaviour

Fedora 22 with the following packages installed:

```
Cython-0.22-1.fc22.x86_64
netcdf4-python-1.1.6-1.fc22.x86_64
numpy-1.9.2-1.fc22.x86_64
python-GridDataFormats-0.2.4-1.fc22.noarch
python-biopython-1.66-3.fc22.x86_64
python-devel-2.7.10-8.fc22.x86_64
python-matplotlib-1.4.3-3.fc22.x86_64
python-networkx-1.9.1-3.fc22.noarch
python-nose-1.3.7-4.fc22.noarch
python-setuptools-17.1.1-3.fc22.noarch
python2-tempdir-0.6-1.fc22.noarch
scipy-0.14.1-1.fc22.x86_64
```

```
./mda_nosetests -v --processes=4 --process-timeout=240
```
### Currently version of MDAnalysis:

0.14.0

**Comment by richardjgowers** [comment]
This is a strange one.  The first test looks like it's returning the wrong shape, but the trace of the returned array matches the expected result. So something changed with how things are summed?

**Comment by orbeckst** [comment]
@rathann can you run the GridDataFormats tests, please?
```
cd GridDataFormats
nosetests -v .
```

I assume that they will pass but I'm groping for straws...

**Comment by rathann** [comment]
Sorry for not replying earlier. I'm unable to reproduce this on current Fedora rawhide (27) with 0.16.0, so closing.
