### ISSUE TITLE
ten2eleven fails with `AttributeError: 'Node' object has no attribute 'value'`

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#862]
### Expected behaviour

I want to upgrade [Becksteinlab/hop/hop/sitemap.py](https://github.com/Becksteinlab/hop/blob/develop/hop/sitemap.py):

``` python
import MDAnalysis as mda
mda.ten2eleven("sitemap.py")
```

This should give me a new file with MDA ≥ 0.11.0 syntax.

### Actual behaviour

Instead it throws an exception:
```
rgstring: self.parameters_default
argstring: self.unit_default
argstring: {}
argstring: lambdae:(e[-1]-e[0])/(len(e)-1)
argstring: lambdae:0.5*(e[:-1]+e[1:])
argstring: lambdam:m[0]
argstring: numpy.diff
argstring: positions=OpenDX.gridpositions(1,self.grid.shape,self.origin,self.delta)
argstring: self.parameters_default
argstring: self.unit_default
argstring: {}
argstring: 'inclusions'
argstring: 'exclusions'
argstring: exclusions
argstring: exclusions
argstring: exclusions
argstring: site_labels
argstring: site_labels
argstring: site_labels
argstring: site_labels
argstring: 10
argstring: 3
argstring: positions=OpenDX.gridpositions(1,g.shape,self.origin,self.delta)
argstring: 3
argstring: g
argstring: g
argstring: 5
argstring: 5
argstring: densities[SELF]
argstring: tuple
argstring: densities[SELF]
argstring: 5
argstring: tuple
argstring: 5
argstring: 3
argstring: 3
argstring: 3
argstring: 3
argstring: 7
argstring: 5
argstring: self
argstring: self
argstring: psffilename
argstring: vmdfilename
argstring: tuple
argstring: tuple
argstring: 3
argstring: 3
argstring: 3
argstring: grid=newgrid
argstring: tuple
argstring: tuple
argstring: *
argstring: MDAnalysis.Universe(*args)
argstring: u
argstring: 3
argstring: delta
argstring: BINS['min']
/Users/oliver/Library/Python/2.7/lib/python/site-packages/MDAnalysis/migration/fixes/fix_framenumberingzerobased.py:30: DeprecationWarning: set_prefix() is deprecated; use the prefix property
  node.set_prefix(comment_string + node.prefix)
argstring: 3
argstring: u.trajectory.n_frames*u.trajectory.delta*u.trajectory.skip_timestep*constants.get_conversion_factor('time','AKMA','ps')
argstring: grid=grid
argstring: 3
argstring: d
argstring: compare(d,cutoff)
argstring: 5
argstring: 3
argstring: 3
argstring: 3
argstring: length='Angstrom'
argstring: dxfile=dx
argstring: eqs_r
argstring: psf
argstring: 3
argstring: delta
argstring: BINS['min']
argstring: lambdae:(e[-1]-e[0])/(len(e)-1)
argstring: lambdae:0.5*(e[:-1]+e[1:])
argstring: lambdam:m[0]
argstring: 3
argstring: 3
argstring: grid=self.g
argstring: 3
argstring: 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/oliver/Library/Python/2.7/lib/python/site-packages/MDAnalysis/migration/ten2eleven.py", line 13, in ten2eleven
    main('MDAnalysis.migration.fixes', ['-w'] + list(files))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/main.py", line 260, in main
    options.processes)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/refactor.py", line 706, in refactor
    items, write, doctests_only)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/refactor.py", line 301, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/refactor.py", line 747, in refactor_file
    *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/refactor.py", line 354, in refactor_file
    tree = self.refactor_string(input, filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/refactor.py", line 386, in refactor_string
    self.refactor_tree(tree, name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib2to3/refactor.py", line 460, in refactor_tree
    new = fixer.transform(node, results)
  File "/Users/oliver/Library/Python/2.7/lib/python/site-packages/MDAnalysis/migration/fixes/fix_torsionclasses.py", line 47, in transform
    if child.value == 'Torsion':
AttributeError: 'Node' object has no attribute 'value'
```

### Code to reproduce the behaviour
```python
# download file
import urllib2
fname = "sitemap.py"
open(fname, "w").write(urllib2.urlopen(
     "https://raw.githubusercontent.com/Becksteinlab/hop/develop/hop/{0}".format(fname)).read())

# try fixing
import MDAnalysis as mda
mda.ten2eleven(fname)
```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)

0.15.0

**Comment by tylerjereddy** [comment]
```python
class Grid(utilities.Saveable):
     pass
```
Is sufficient to reproduce the error. Also noticing that 
```python
class Nobulk:
    pass
```
Is getting adjusted to `class Nobulk():`, which probably shouldn't happen.

I have a flight at 2am and am travelling across the US for the next two weeks for work, but will put this on my list in any case.

**Comment by tylerjereddy** [comment]
Sounds fair -- we haven't really seen that much noise in recent months about it if I'm not mistaken.
