### ISSUE TITLE
Problem with reading/writing CONECT records in PDB files with many atoms

### ISSUE THREAD

**Issue by BartoszBartmanski** [MDAnalysis/mdanalysis#988]
### Expected behaviour

Reading in a pdb file using the standard `MDAnalysis.Universe("file_name.pdb")`
### Actual behaviour

Fails with the following error message:

```
Traceback (most recent call last):
  File "./run_simulation.py", line 19, in <module>
    md_simulation.use_packmol()
  File "/sansom/s118/shil4444/Documents/Influenza_model/Input_files/md_simulation.py", line 405, in use_packmol
    shapes.add_rpo(ip)
  File "/sansom/s118/shil4444/Documents/Influenza_model/Input_files/shapes.py", line 462, in add_rpo
    u_vesicle = MDAnalysis.Universe(ip["filename"]+".pdb")
  File "/sansom/s118/shil4444/.local/lib/python2.7/site-packages/MDAnalysis-0.15.1.dev0-py2.7-linux-x86_64.egg/MDAnalysis/core/AtomGroup.py", line 4339, in __init__
    self._topology = p.parse()
  File "/sansom/s118/shil4444/.local/lib/python2.7/site-packages/MDAnalysis-0.15.1.dev0-py2.7-linux-x86_64.egg/MDAnalysis/topology/PDBParser.py", line 90, in parse
    bonds = self._parsebonds(atoms)
  File "/sansom/s118/shil4444/.local/lib/python2.7/site-packages/MDAnalysis-0.15.1.dev0-py2.7-linux-x86_64.egg/MDAnalysis/topology/PDBParser.py", line 181, in _parsebonds
    atom, atoms = _parse_conect(line.strip())
  File "/sansom/s118/shil4444/.local/lib/python2.7/site-packages/MDAnalysis-0.15.1.dev0-py2.7-linux-x86_64.egg/MDAnalysis/topology/PDBParser.py", line 215, in _parse_conect
    "record: {}".format(conect))
RuntimeError: Bond atoms aren't aligned proberly for CONECT record: CONECT100001100000100002100007
```
### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe("Flu_membrane_capsule.pdb")
```

[Flu_membrane_capsule.txt](https://github.com/MDAnalysis/mdanalysis/files/474513/Flu_membrane_capsule.txt)
### Currently version of MDAnalysis:

0.15.1-dev0

**Comment by orbeckst** [comment]
I think the problem is that you have so many atoms that the PDB format runs out of atom indices and then the CONECT records become meaningless. If you remove the CONECT records 
```
wget -O Flu_membrane_capsule.pdb  https://github.com/MDAnalysis/mdanalysis/files/474513/Flu_membrane_capsule.txt
grep -v CONECT Flu_membrane_capsule.pdb > Flu_membrane_capsule_noCONECT.pdb
```

then it can be read successfully:
```python
>>> import MDAnalysis as mda
>>> u = mda.Universe("./Flu_membrane_capsule_noCONECT.pdb")
>>> print(u.atoms.n_atoms)
188513
```

Now, it seems that you *wrote* this PDB file with MDAnalysis (is this true?) and it was the MDAnalysis PDB write that put the CONECT records there. I think this indicates a bug in the **PDBWriter** in that it should not write CONECT records if it generates an illegal PDB file.

**Comment by orbeckst** [comment]
As a workaround, can use other formats in your workflow, such as GRO?

**Comment by richardjgowers** [comment]
I think there's 2 things here, the PDBParser should still work, it should just give up on trying to read the CONECT records (with a warning). And it looks like the PDBWriter shouldn't have made an unusable file.

**Comment by BartoszBartmanski** [comment]
The way that I create this file is by using packmol and then importing it into MDAnalysis to change it. The error message I received was when I imported it again. But, thank you for the advice.

Best,

Bartosz
________________________________________
